### ISSUE TITLE
Serve not working in Ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by cschweda** [zeit/serve#111]
Not sure if this is a known issue -- or an issue with my specific configuration -- but even after installing globally in Ubuntu 16.04 64 via:

```npm i serve -g```

And then running against files in a static directory (a Vue.js build):

```serve ./dist```

The terminal displays that the server started, gives the two sets of URLs, and then goes right back to the command line. 

*No errors -- but it immediately stops serving.*

Anyone else see this?

(Just as a sanity check, I installed ```http-server``` gloabally via npm, ran it against the same static directory, and all is well. Files are served fine via localhost.)

Thoughts?

PS -- Not that it should matter, but I'm running Ubuntu via VMWare on a Windows box with 4 gigs ram to the vm.
```
cschweda@ubuntu:~/Webdev/test01$ serve dist

   ┌─────────────────────────────────────────────────────┐
   │                                                     │
   │   Serving!                                          │
   │                                                     │
   │   - Local:            http://localhost:3000         │
   │   - On Your Network:  http://192.168.229.131:3000   │
   │                                                     │
   │                                                     │
   │                                                     │
   └─────────────────────────────────────────────────────┘

cschweda@ubuntu:~/Webdev/test01$ node -v
v7.5.0
cschweda@ubuntu:~/Webdev/test01$ npm -v
4.1.2
cschweda@ubuntu:~/Webdev/test01$ 
```

**Comment by DavidBruant** [comment]
I can confirm this bug

**Comment by DavidBruant** [comment]
I tried and had the same bug with 
serve@3.3.0
serve@3.2.10
serve@3.0.0
serve@2.4.4 
serve@2.4.3 

For some reason, `npm start` works on [this project](https://github.com/dtc-innovation/dataviz-finances-gironde/blob/7accb84e416571be873ed66254609762b84b635b/package.json#L12). No clue what's different beyond being used as an npm script.

**Comment by cschweda** [comment]
Yep -- this works when run via npm -- but not on the command line.

package.json:

```
  "start": "serve ./dist --static",
```

Then:

```
cschweda@ubuntu$ npm run start
```

Works as expected.

However:

```
cschweda@ubuntu$serve ./dist --static
```

Doesn't work. Simply goes right back to the command line.

```
cschweda@ubuntu$ serve -v
3.3.1
```

**Comment by jannisch** [comment]
I can confirm this issue on Void Linux with serve 3.3.1.

**Comment by disquisition** [comment]
Testing this out, it looked like the issue was that when on Linux and `xclip` isn't installed, the `copy-paste` package can raise a `SIGPIPE` when it attempts to copy to the clipboard. The reason there's no error is that the process seems to terminate before the error lister has a chance to fire.

(Still not sure why this isn't a problem when you run `serve` via `$ npm run start`...)

**Comment by cschweda** [comment]
Yep. Installed xclip -- and all is well:

```
cschweda@ubuntu:~$ sudo apt-get install xclip
```

Then:
```
cschweda@ubuntu:~$ serve
```

And everything works fine.

**Comment by cubodehelio** [comment]
serve -v
3.4.0

Stop working in `Linux Mint 17.2` after update.  It just get back to the console with no output at all.

**Comment by cschweda** [comment]
Did you try installing xclip as mentioned above?

```
sudo apt-get install xclip
```

**Comment by cubodehelio** [comment]
Thanks @cschweda yes, that solves the problem sorry.
