### ISSUE TITLE
Programmatic API and feature request

### ISSUE THREAD

**Issue by Swizz** [zeit/serve#117]
Hi there !

It is possible to consider the need of silent option ? 
Which allow to do not print anything in the console (copy to clipboard too ?)

Then, could it be a way using the Programmatic API to fetch the host and port on the server is running ? 
(Not a real need, could be done when options are given).

I am working on a build tool plugin, who have a standardised log.

Cheers,

**Comment by derhuerst** [comment]
See #113 for the programmatic API.

**Comment by Swizz** [comment]
Yes, I seen this. I hesitated to post in or create a new issue.
I can split this issue. The main request remaining the silent mode option (also with the cli).

**Comment by leo** [comment]
Please add an issue for the silent option!
