### ISSUE TITLE
Add silent mode option

### ISSUE THREAD

**Issue by Swizz** [zeit/serve#118]
_This issue follows #117._

Hi,

Can you add a silent option to the cli, which made Serve does not write anything in the terminal ?

Is this option need to turn off the "copy to clipboard" capabilities too ?

Cheers,

**Comment by leo** [comment]
Released in [4.0.0](https://github.com/zeit/serve/releases/tag/4.0.0)

**Comment by iamstarkov** [comment]
yay

**Comment by roccomuso** [comment]
Is silent activated by default?
I'd like to have a verbose mode.

**Comment by leo** [comment]
No, silent is not enabled by default.
