### ISSUE TITLE
arguments: -s does not do the same thing as --single

### ISSUE THREAD

**Issue by SamNazar** [zeit/serve#128]
to reproduce: `serve -s dir` where dir contains an index.html 
Try visiting `localhost:5000/fakeurl`
You will receive a `not found` 404 rather than index.html

Repeat this with `serve --single dir` and the expected result (contents of index.html) are served.

The `-s` argument is ignored while `--single` works.

**Comment by lukeed** [comment]
Just discovered the same issue.

**Comment by lukeed** [comment]
However, in my case, `serve dir -s` works, but `serve -s` did not. Using `--single` in all scenarios is most consistent.

**Comment by leo** [comment]
[Fixed!](https://github.com/zeit/serve/releases/tag/5.0.2) 🎉
