### ISSUE TITLE
serve -s [bad dir] freezes

### ISSUE THREAD

**Issue by gaearon** [zeit/serve#131]
```
npm i -g serve@5.0.2
serve -s badpath
```

Expected: it tells me `badpath` ain’t there.
Actual: nothing happens.

<img width="312" alt="screen shot 2017-03-11 at 9 41 13 pm" src="https://cloud.githubusercontent.com/assets/810438/23827084/797ad24c-06a3-11e7-9c0e-a1a2264748eb.png">

Node 7.7.2.

**Comment by leo** [comment]
Fixed in https://github.com/zeit/serve/pull/132 and released with [5.0.3](https://github.com/zeit/serve/releases/tag/5.0.3). 🎉

**Comment by gaearon** [comment]
Thanks for quick fix!
