### ISSUE TITLE
error "Can't remove headers after they are sent"

### ISSUE THREAD

**Issue by eduplessis** [zeit/serve#145]
`_http_outgoing.js:394`
`    throw new Error('Can\'t remove headers after they are sent');`
`     ^`
`Error: Can't remove headers after they are sent`
`    at ServerResponse.removeHeader (_http_outgoing.js:394:11)`
`    at clearHeaders (C:\Users\edupl\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:908:9)`
`    at SendStream.error (C:\Users\edupl\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:292:3)`
`    at SendStream.headersAlreadySent (C:\Users\edupl\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:404:8)`
`    at SendStream.send (C:\Users\edupl\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:625:10)`
`    at onstat (C:\Users\edupl\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:737:10)`

**Comment by skiano** [comment]
I just rolled back to version 5.0.4 and it fixed this for me

**Comment by eduplessis** [comment]
ok ... thanks gonna try this

**Comment by leo** [comment]
How did you get this error? What's your setup and how does the command look?

**Comment by skiano** [comment]
@leo thanks!

**Comment by leo** [comment]
:pray: 😊
