### ISSUE TITLE
SyntaxError: Unexpected token { on const { coroutine} and const { red }

### ISSUE THREAD

**Issue by cjromb** [zeit/serve#155]
I've never filed an issue on an npm package before, so not sure if this is the right way to do it.  This may not turn out to be an issue with serve, but I can't figure out where else to look.

I'm on a mac and ran this command:

sudo npm install -g serve

When it was done, I tried

serve help

I also tried serve -s build (which is the directory I wanted to serve static pages from)

No matter what I type after serve, same error.  

SyntaxError.  It's complaining about line 11 and 13.

I tried removing the braces from around those two constants, but then got another error:

***************
let current = process.cwd();
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
****************

finally I ran
npm uninstall serve
and
sudo npm install serve -g

and then reinstalled it, in case I had an old version hanging around.

I installed it again.  Same errors.

Thank you in advance for any guidance you can give me.

**Comment by leo** [comment]
Your version of Node.js is lower than LTS. You need at least LTS in order to be able to use this project. You can get it on [here](https://nodejs.org/en/) with the left one of the big green buttons.

**Comment by cjromb** [comment]
Thank you!  I apologize for not figuring this out on my own.
