### ISSUE TITLE
Not working on Node 4

### ISSUE THREAD

**Issue by gaearon** [zeit/serve#157]
Not sure this is intentional, but it breaks on Node 4:

```
/usr/local/lib/node_modules/serve/bin/serve.js:11
const {coroutine} = require('bluebird')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

Since we recommend `serve` in CRA, and CRA supports Node 4, this is an issue for us.

**Comment by AbeEstrada** [comment]
Looks intentional:

`package.json`

```
"engines": {
  "node": ">=6.9.0"
}
```

**Comment by gaearon** [comment]
😞

**Comment by leo** [comment]
@gaearon Why does CRA support Node 4? The latest LTS version of Node is 6.

**Comment by gaearon** [comment]
It used to be LTS until recently, and we haven't dropped the compatibility yet. We intend to in a future release in a month or os.

**Comment by leo** [comment]
@gaearon I see! Should be fairly easy to implement. But once CRA supports latest LTS, we'll do the transition. I want native `async` and `await` once the LTS for 8 comes out.

**Comment by leo** [comment]
Oh, I just noticed that [micro](https://github.com/zeit/micro) only supports the current LTS as well (just like all of our projects). Can you live these 30 days (or so) with the current support?

**Comment by gaearon** [comment]
Yea, I guess it’s fine.

**Comment by leo** [comment]
❤️

**Comment by hanishassim** [comment]
@gaearon How to solve this? I got the same error..

**Comment by leo** [comment]
@hanishassim Upgrade your Node.js version by downloading the latest one [here](https://nodejs.org/en/)... 😊

**Comment by hanishassim** [comment]
@leo Solved it! Thanks.

Perviously I'm using the distro-stable version, v4.x, so I've force update it using NodeSource PPA

**Comment by yeyuqiu** [comment]
I came up with the same error. After upgrading the Node.js version, it's solved.
