### ISSUE TITLE
Improper Signal Handling within a Docker Container

### ISSUE THREAD

**Issue by ckeeney** [zeit/serve#159]
If you try to stop a docker container, docker issues the container a `SIGINT`, followed by a `SIGKILL` if the container is still running in 10s.

Due to an upstream linux kernel bug, containers killed by `SIGKILL` can result in the docker host to completely crash, requiring a power cycle.  See [my comment](https://github.com/docker/docker/issues/5618#issuecomment-275277828) and others on the very long thread about this issue.

Something like this would solve the problem:
```js
function shutdown() {
    logger.log('info', 'Graceful shutdown.');

    httpServer.close();
    if (httpsServer) {
        httpsServer.close();
    }

    process.exit();
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
```
copied and pasted from [this comment](https://github.com/docker/docker/issues/5618#issuecomment-275630536).

**Comment by ckeeney** [comment]
I have created a Docker Image for illustrating this problem:

```
docker run -d -p 3000:3000 ckeeney/servejs
````

And you can verify that serve is running in your browser at [localhost:3000](http://localhost:3000/).  You will see a directory listing of alpine linux root filesystem.

Now time to stop the container:
```
$ time docker stop e1b401539e2d 
e1b401539e2d
docker stop e1b401539e2d  0.01s user 0.01s system 0% cpu 10.406 total
```

The entire dockerfile is just
```Dockerfile
FROM node:alpine
RUN npm install -g --progress=false serve
EXPOSE 3000
CMD serve -s / -p 3000%
```

**Comment by leo** [comment]
Any recommendation for what we should do to improve this?

**Comment by JamesKyburz** [comment]
@ckeeney I don't think the process handler is called in serve. This because docker stop sends the signal to process with pid 1. Using cmd alone will spawn with the shell and serve will run in another process.

Could you test with a new docker file making sure `serve` runs on pid 1?

I have done this in the past like so

```
entrypoint ["./node_modules/.bin/serve", "-s", "/", "-p", "3000"]
cmd [""]
```

**Comment by motiejunas** [comment]
Having the same issue when stopping containers initiated with `docker-compose up`. All containers shuts down immediately except the ones using `serve` (takes 10 seconds).
