### ISSUE TITLE
Option for enabling HTTPS

### ISSUE THREAD

**Issue by Queatz** [zeit/serve#178]
Any way to do it or is it planned?

**Comment by albinekb** [comment]
It's recommended to add nginx proxy or similar as SSL termination, it's not performant enough in node.

**Comment by albinekb** [comment]
https://github.com/zeit/micro/issues/224

**Comment by DanielBaird** [comment]
+1 for this request.

For me `serve` has a use case of "quickly check something local in a browser".  In that situation it's much better to have SSL built in, even if it's slow. When I'm working on a javascript SPA or a D3 visualisation, or I'm quickly looking over a site design for a colleague, I want a quick one-liner that works immediately -- I don't want to take the time to set up an nginx https proxy.

Maybe it's out of scope or more work than the devs want to do, but I think "it would be slower than nginx" isn't an argument against adding TLS/HTTPS to this tool.

**Comment by mrmartineau** [comment]
@DanielBaird did you ever find something that would do SSL like `serve`? I need something to test Service Workers on my Jekyll site..

**Comment by DanielBaird** [comment]
@mrmartineau Best so far is Caddy ( https://caddyserver.com ), where something like

```
sudo caddy -host myproject.com
```
...will start serving the current dir at myproject.com via http and https using a cert from letsencrypt.

**Comment by albinekb** [comment]
@mrmartineau Do you need ssl just for `localhost`?

**Comment by mrmartineau** [comment]
@DanielBaird thanks for the tip, I will give it a try.

@albinekb yes.

Both, I've been using `firebase serve` to do this but it is too complicated to setup for many projects.

**Comment by leo** [comment]
I'm happy to accept a PR for this!

**Comment by kitsunekyo** [comment]
maybe a collaboration /merge would be great between the two of you guys.
I've been using this package until i've heard of "serve".

https://github.com/indexzero/http-server

**Comment by justanotherdot** [comment]
I've a semi-working branch for this and I'll try to submit a PR as soon as I sand off some of the rough edges. :slightly_smiling_face:

**Comment by devinrhode2** [comment]
I struggled to get caddy to work. I ended up using http-server instead (`npm install -g http-server`)

**Comment by Tapudp** [comment]
Thank you so much @devinrhode2 , after a long day searching finally `http-server` worked well. 👍
