### ISSUE TITLE
Can't select port

### ISSUE THREAD

**Issue by ayroblu** [zeit/serve#182]
I was using create react app, decided to use serve since its what it recommends at the end, but since I usually have something running on port 5000, I wanted to use another port. However that didn't work
MacOS Sierra
Node: v7.9.0
Serve: v5.1.4

Command:
`serve -s -p6000 build`

I closed things and serve -s build seemed to work on port 5000

**Comment by pablopunk** [comment]
It seems the browsers detect port 6000 as an unsafe port so they refuse to connect to it (see [this for chrome](https://superuser.com/questions/188006/how-to-fix-err-unsafe-port-error-on-chrome-when-browsing-to-unsafe-ports) and [this for safari](https://discussions.apple.com/message/7574098#message7574098))

Using another port should solve the problem:

```shell
serve -s -p6001 build
serve -s -p5999 build
```

**Comment by leo** [comment]
You should also leave a space after the flag name: `-p 6001`
