### ISSUE TITLE
Add support for 'basepath' option

### ISSUE THREAD

**Issue by wilsonpage** [zeit/serve#184]
As per [nws docs](https://github.com/knpwrs/nws#usage)

> If you want all requests to resolve to a base path (i.e. http://localhost:3030/basepath) without having to place all files into a src/basepath sub-directory, use the -b flag:
>
> `nws -b basepath`

This means allows you to mount the server on different path contexts.

**Comment by leo** [comment]
Thanks for the effort you've put into researching this, but I think the project is already way too complex. In turn, I don't think it's good idea to support such an edge case.

I hope you understand that! 😊

**Comment by conorwsullivan** [comment]
Hi leo, can you document how to implement this using rewrites or redirects? It seems like it should be straightforward to do so but I haven't been able to do it correctly.

**Comment by disog** [comment]
See this https://github.com/vercel/serve/issues/784#issuecomment-1986090459
