### ISSUE TITLE
reloading on routes will get error

### ISSUE THREAD

**Issue by SHZhao74** [zeit/serve#194]
I use `$serve -s build -p 80` to deploy my react app with react-router.
When I reload the  page on index route (`/`) and login page (`/login`), it works fine.  
However, my website gets error as I refresh on other routes, for example `/book/123456`.  

Because no matter what the request is, the browser always gets HTML file.  
Thus, both of the content in `main.css` and `main.js` are HTML, and the browser error.
![screen shot](https://i.stack.imgur.com/xOu6J.png)

Did I lost any configurations?

**Comment by leo** [comment]
`serve` only responds with `index.html` if it doesn't find a file - so I'm happy to accept a PR that makes it find our files. 😊
