### ISSUE TITLE
Downloaded serve for first time, kept getting errors w/ fs-promise

### ISSUE THREAD

**Issue by mardisworld** [zeit/serve#195]
Kept getting: 
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support 
So I went into serve package and changed everything from 'fs-promise' to 'mz'. That seemed to work enough to let me build.

**Comment by leo** [comment]
That's a deprecation warning, not an error. Just ignore it while installing 😊

**Comment by mardisworld** [comment]
It wouldn't build without it.

**Comment by albinekb** [comment]
The warning will be gone when https://github.com/zeit/serve/pull/199 is released :) @mardisworld
