### ISSUE TITLE
Issues for directories with "#" character

### ISSUE THREAD

**Issue by danshao** [zeit/serve#202]
When I try to serve a directory with subdirectories that have a '#' sign, I am unable to browse into the subdirectory with the '#' character.

`$> mkdir asldkfja#\#ECACE/`
`serve`

I get `Not Found` at `http://192.168.1.10:5000/asldkfja##ECACE`

**Comment by leo** [comment]
Directories should never contain the `#` character, as it's being used on web pages or selecting an element or setting a specific value ([more details](https://www.w3schools.com/jsref/prop_loc_hash.asp)).
