### ISSUE TITLE
Error Run serve

### ISSUE THREAD

**Issue by lmdelgallego** [zeit/serve#207]
`/usr/local/lib/node_modules/serve/bin/serve.js:11`
`const { coroutine } = require('bluebird')`
 `     ^`

`SyntaxError: Unexpected token {`
`    at exports.runInThisContext (vm.js:53:16)`
 `   at Module._compile (module.js:373:25)`
  `  at Object.Module._extensions..js (module.js:416:10)`
   ` at Module.load (module.js:343:32)`
   ` at Function.Module._load (module.js:300:12)`
   ` at Function.Module.runMain (module.js:441:10)`
   ` at startup (node.js:139:18)`
   ` at node.js:974:3`

**Comment by leo** [comment]
Your version of node is too old, it needs to be at least LTS (see their homepage).
