### ISSUE TITLE
Add flag for serving SPAs

### ISSUE THREAD

**Issue by ro-savage** [zeit/serve#208]
Would be great to a flag for SPAs that adds two features

- [x] Changes caching options so that index.html has a cache of 0, and all other files have the amount passed in the --cache flag (and maybe a sensible default if not cache flag was passed)
- [x] Changes the folder redirect rule so that all files that aren't found get redirected back to /index.html

Happy to make PR for this.

**Comment by ro-savage** [comment]
Looks like you already have the option to always save index under -single.

So how about when using this flag, we add better caching defaults?

**Comment by leo** [comment]
Moving this discussion to the PR
