### ISSUE TITLE
cors not working

### ISSUE THREAD

**Issue by bigearsenal** [zeit/serve#213]
I run my app, which is build by create-react-app with flag cors, but i still get error "No 'Access-Control-Allow-Origin' header is present on the requested resource."
`serve -s var/www/bigvalut.ru/build --cors -p 80`
here is my server
http://181.215.98.221/

**Comment by leo** [comment]
Are you sure [those](https://github.com/zeit/serve/blob/ade5a147901bac4ffb7d59835e4c89955ee2044a/lib/server.js#L22) are valid for you? Can you also check the headers by yourself?
