### ISSUE TITLE
Explicit cache bust

### ISSUE THREAD

**Issue by KrekkieD** [zeit/serve#224]
Would it be possible to add a param that explicitly sets no-cache headers? 

Reason being is I use `serve` in a development deployment scenario for reviewing purposes. The people that review the app are not tech savvy so I have to remind them every time to refresh the page properly. Next to that, some browsers have very sticky default caching behaviour, which makes it even worse.

I'm currently serving with `serve -s -c 0` which does set the max-age to zero, but that doesn't seem to be behaving the same as no-cache headers.

**Comment by leo** [comment]
We should set the "no-cache" one if `-c` is `0` maybe?

**Comment by leo** [comment]
Fixed in https://github.com/zeit/serve/pull/245

**Comment by jespertheend** [comment]
is no longer working?
