### ISSUE TITLE
Ignore list doesn't block requests

### ISSUE THREAD

**Issue by paulirish** [zeit/serve#229]
My company does security scans and folders i've `serve`'d get caught because the `.git` folder is exposed.

I see `.git` is in the default ignore list, but that appears to only affect rendering the web UI. Serving of files isn't affected by the `ignore` configuration, but that's exactly what I want.

Thanks!

**Comment by leo** [comment]
Great find, thanks! Will fix tomorrow (after midnight here in germany)... 😊

**Comment by leo** [comment]
Fixed in [5.2.4](https://github.com/zeit/serve/releases/tag/5.2.4)! 🎉  Thanks again for reporting it!

**Comment by paulirish** [comment]
Confirmed fixed. thanks!

**Comment by megaslug** [comment]
It appears that as of 5.2.4 my project build times increased by 50%, so had to roll back to 5.2.3. Is it just me or is there anyone else reporting the same?

**Comment by leo** [comment]
@megaslug I can't think of any way in which this project could affect your build time. It's not part of your build flow. The only purpose of it is to provide a webserver for serving your files.
