### ISSUE TITLE
`index.htm` isn't served as directory index

### ISSUE THREAD

**Issue by joshgillies** [zeit/serve#23]

**Comment by terkelg** [comment]
Is this the reason why index.html can't link to files relative to the current directory? Like in this example https://dist-myryxjqyxh.now.sh/1, where index.html can't find the stylesheets and JavaScript files?

**Comment by leo** [comment]
Not willing to support this, sorry! It's a freaking old extension originating from the time in the DOS world where only 3 extension chars were allowed. Please use .html!
