### ISSUE TITLE
Introduce tests

### ISSUE THREAD

**Issue by leo** [zeit/serve#233]
We need automated tests to ensure that the code always works correctly!

**Comment by MarkRabey** [comment]
I'd love to help out with this!

**Comment by leo** [comment]
@MarkRabey Wonderful! I'd love to accept a pull request.

**Comment by MarkRabey** [comment]
@leo great, I'll start with just adding a testing framework and setting it up. Any preferences? I was thinking [Mocha](https://mochajs.org/).

**Comment by leo** [comment]
@MarkRabey AVA, please 😊

**Comment by leo** [comment]
✅ thanks @maxbeatty
