### ISSUE TITLE
Improve listing files with long name

### ISSUE THREAD

**Issue by iwazaru** [zeit/serve#237]
I'm using **serve** to host and share files that may have long names. Current presentation only displays the first characters of the file's name in most cases, which can lead to confusion.

![Listing files](https://user-images.githubusercontent.com/5627688/27691117-63fe3210-5ce3-11e7-94f1-610e4d7a9bb6.png)

I would love to have an option that would allow displaying one file per line, with the full name of the file shown.

**Comment by tohjustin** [comment]
@leo I think this should be a relatively straightforward change, should I just add a button to toggle the layout? Also, do you have any mock ups that I could work with? =0

**Comment by leo** [comment]
Fixed in https://github.com/zeit/serve/pull/276

**Comment by sunlei4076** [comment]
not work in ios device
