### ISSUE TITLE
Stopping the app from the terminal

### ISSUE THREAD

**Issue by jer8** [zeit/serve#247]
Is there an option we can use on the terminal to stop serving the app?

**Comment by leo** [comment]
CTRL+C - just like with any other process started from there 😊

**Comment by jer8** [comment]
Sorry, i should've clarified more. Any option to have my app module be served inside my parent app (so that I won't have to have a terminal open as long as the app is live) but still be able to stop it on the terminal? Or do I have to kill the process myself 🗡

**Comment by leo** [comment]
I'm not exactly sure what you're asking for, sorry. But you can use the [programmatic API](https://github.com/zeit/serve#api) or maybe `serve ../` helps? 😊
