### ISSUE TITLE
Feature to serve directory from File explorer

### ISSUE THREAD

**Issue by itaditya** [zeit/serve#252]
Wouldn't it better if user can right click in the folder and have the folder **served** easily.
This would be especially helpful in two scenarios - 
1. When a frontend beginner who use terminal very rarely needs to run site on localhost.
2. When people wants to run a static server for file sharing.

**Comment by leo** [comment]
`serve` is a command line interface that only runs when you run the command. In turn, it's not possible for us to add such a feature. You can drag the directory into the terminal after typing in `serve` followed by a space. 😊

**Comment by itaditya** [comment]
No I can make this feature, I just think we can expand the scope of the **serve** utility.
