### ISSUE TITLE
Suggestion: SPA should 404 on fetching obvious non-html assets

### ISSUE THREAD

**Issue by transitive-bullshit** [zeit/serve#257]
For SPAs, a common issue I've run into is that as hashed static resources change between deployments, a stale client requests an old asset (oftentimes due to a client-side service worker), and failing to find the static resource, `serve` naively returns `index.html` which is almost never what you want and leads to weird client-side errors.

See [here](https://github.com/PolymerElements/app-storage/issues/81) and [here](https://github.com/react-boilerplate/react-boilerplate/issues/1676) for solid descriptions of the general problem aside from `serve`.

I realize this is how most static file serving solutions work, but I know we can do better for the majority use case, where the requested resource is in a blacklist of common content-types (e.g., `js`, `css`, `png`, `jpg`, `svg`, etc).

I'd like to propose adding an optional flag to augment SPA mode whereby these types of resource requests return 404 if not found, instead of naively returning `index.html`.

Thoughts?

**Comment by sergiodxa** [comment]
In a SPA your 404 is usually being rendered client side, that means you need to first get your `index.html`, start your app and then check the URL to render your app or render a 404.

**Comment by fisch0920** [comment]
@sergiodxa the whole point here is that the server isn't returning a 404 -- it's returning `index.html` for a missing static asset as opposed to returning a 404 which could be gracefully handled client-side.

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `headers` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).

**Comment by minhdao88** [comment]
Sorry to bother but I just stumbled upon this issue recently, and after checked serve-handler documentation I still don't understand how to config it to return 404 status instead of the HTML file. 

Any help would be greatly appreciated.
