### ISSUE TITLE
SPA caching is incorrectly applied to index.html

### ISSUE THREAD

**Issue by evangoer** [zeit/serve#258]
Per #209: in SPA mode, `serve` should be serving up assets with the specified cache value, but `./index.html` is special-cased to have no cache. Instead, serve appears to be serving up all files with the specified `--cache` value.

```
$ ./node_modules/.bin/serve --version
6.0.6
$ ./node_modules/.bin/serve --single --cache 12345678000


$ curl -I localhost:5000/
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Accept-Ranges: bytes
Cache-Control: public, max-age=12345678
Last-Modified: Tue, 22 Aug 2017 17:33:37 GMT
ETag: W/"c-15e0b01bd68"
Content-Length: 12
Vary: Accept-Encoding
Date: Tue, 22 Aug 2017 17:57:09 GMT
Connection: keep-alive
$ curl -I localhost:5000/index.js
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=12345678
Last-Modified: Tue, 22 Aug 2017 17:33:50 GMT
ETag: W/"13-15e0b01f030"
Content-Type: application/javascript
Content-Length: 19
Vary: Accept-Encoding
Date: Tue, 22 Aug 2017 17:57:23 GMT
Connection: keep-alive
```

**Comment by evangoer** [comment]
However, if you hit a path that isn't the physical `index.html` file or an asset file, the `index.html` contents *do* get returned with a max-age of 0:

$ curl -I localhost:5000/no-physical-file-at-this-path
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Tue, 22 Aug 2017 17:33:37 GMT
ETag: W/"c-15e0b01bd68"
Content-Type: text/html; charset=UTF-8
Content-Length: 12
Vary: Accept-Encoding
Date: Tue, 22 Aug 2017 18:01:57 GMT
Connection: keep-alive

**Comment by leo** [comment]
Have you read [this](https://github.com/zeit/serve/pull/209)?

**Comment by evangoer** [comment]
Yes, I have. And I've read the commit diffs for #209. Unfortunately, there's a bug.

```
$ curl -I localhost:5000/
Cache-Control: public, max-age=12345678
```

**Comment by evangoer** [comment]
For clarity, here are the three cases side-by-side:

```
$ curl -I localhost:5000/index.js
Cache-Control: public, max-age=12345678                 // correct
$ curl -I localhost:5000/no-physical-file-at-this-path
Cache-Control: public, max-age=0                        // correct (though probably should be no-cache?)
$ curl -I localhost:5000/
Cache-Control: public, max-age=12345678                 // incorrect
```

**Comment by leo** [comment]
Oh. Are you using the `-s` flag?

**Comment by evangoer** [comment]
Yup, running with `-s`.

**Comment by ericf** [comment]
I'm curious if there's any update on this issue?

**Comment by leo** [comment]
Seems like we need to fix it! We're not correctly applying the right caching values.

**Comment by leo** [comment]
Fixed in https://github.com/zeit/serve/pull/269 - will go out once https://github.com/zeit/serve/pull/274 is merged!
