### ISSUE TITLE
[question] how to use --ignore

### ISSUE THREAD

**Issue by matthewdias** [zeit/serve#264]
What is the syntax for adding ignored files and directories from the command line? I can't seem to get it to work.

**Comment by ragingwind** [comment]
Ignored files using comma-separated values. It might works

```
serve -i node_modules,test,dist
```

**Comment by matthewdias** [comment]
doesn't seem to have any effect

**Comment by ragingwind** [comment]
Let me show commands you used

**Comment by matthewdias** [comment]
`serve -i Applications,Books,Comics,Desktop,Documents,Downloads,Dropbox,Google\ Drive,Library,Pictures,Public,VirtualBox,VMs,floobits`

attempted with quotes, removing `Google Drive` altogether, etc. it still serves all subdirectories.

**Comment by mcansh** [comment]
Folders need to include / on the end of them so `serve -i Applications/,Books/` etc

**Comment by matthewdias** [comment]
thanks!
