### ISSUE TITLE
feature: Option to serve unfound routes as an entry file (e.g. for SPA's)

### ISSUE THREAD

**Issue by alexilyaev** [zeit/serve#266]
When running a web app (single page application) with HTML5 history API, for routes to work properly on reload, the server must serve the index file on unfound routes.

This is implemented in live-server as `--entry-file=PATH`:  
https://github.com/tapio/live-server

**Comment by nicolasparada** [comment]
`-s` or `--single`

**Comment by alexilyaev** [comment]
Right, I guess I had a different version of serve installed, indeed works.
