### ISSUE TITLE
Add url redirects

### ISSUE THREAD

**Issue by mrmartineau** [zeit/serve#27]
I'd like to be able to add some url redirects (e.g. 301) to my app. I know this feature is not supported at the moment, but I think it would be a useful addition. I originally submitted this to [now-serve](https://github.com/zeit/now-serve/issues/20)

Thanks

**Comment by leo** [comment]
This is too much for a tiny package like "serve". Please use client-side redirects!

**Comment by mrmartineau** [comment]
@leo I understand why this has been closed, but client-side redirects do not return 301/302 responses making them useless for a proper app - unless there's something I'm missing. If it is not possible with `serve`, would it be possible to use something else to manage redirects because you now uses nginx? I realise this may not make sense, it is only because I have limited experience with servers... :)

**Comment by romuloalves** [comment]
@mrmartineau Is this useful for you?!
[https://github.com/vdanchenkov/now-redirect](https://github.com/vdanchenkov/now-redirect)

**Comment by timneutkens** [comment]
https://github.com/timneutkens/now-redirect is a lot smaller ❤️
