### ISSUE TITLE
Any option for live-reloading?

### ISSUE THREAD

**Issue by johnunclesam** [zeit/serve#271]
Any option for live-reloading?

Something like this? https://github.com/tapio/live-server

**Comment by barinali** [comment]
@leo what do you think about this feature request? I'm not sure having it in `serve`. Do you consider extending `serve` in this way? If so, I'd like to create a pull request for this.

**Comment by leo** [comment]
I think this is too much for core. People can wrap `serve` if they want it... 😊

**Comment by coldtelling** [comment]
@revelt a bit late to the party but there's [browser-sync ](https://github.com/BrowserSync/browser-sync)

**Comment by tonypee** [comment]
i think reloading is important too - i might give it a crack this morning.. lets see

**Comment by shannonmoeller** [comment]
There are several options out there, but none suited my purpose, so I made one.

**Comment by lukejacksonn** [comment]
I wanted to understand how live reloading actually worked once. So I tried rolling my own in a determined _zero dependency_ fashion with the aim of learning as mush as possible. I hit a wall pretty quick at the web socket connection, implementing this myself was not something I wanted to do so I searched for an alternative method for the dev server to communicate with the browser.

I stumbled across `connection-type: text/event-stream` which creates a one way stream of data that the browser that can subscribe to using the `EventStream` API. Both these features are native to their respective platforms (node and the browser) so it barely adds anything to either codebase.

Now all that remains to be done by the server when `--watch` option is present is to:

- Inject the subscriber code into the html document that is being served

```
file += `
  <script>
    const source = new EventSource('http://localhost:5000');
    source.onmessage = e => location.reload(true);
  </script>
`
```

- Watch the file system and send a message to the browser on any change

```
fs.watch(path.join(cwd, root), { recursive: true }, () =>
  sendMessage(res, "message", "reloading page")
);
```

I ended up adding this feature to my own little [dev server](https://github.com/lukejacksonn/servor) and it has been working well so far. Recently I came back to use `zeit/serve` for a project thinking that it had live reload but found it doesn't!

Would you be interested in me making a PR that includes the above implementation to see how it might look? I agree with @leo that a full blown web socket implementation would be too much for core.. but this approach offers quite a bit of bang for its buck.

**Comment by hossameldeen** [comment]
I think `now dev` now does what's needed, if I understood correctly.

**Comment by ltfschoen** [comment]
I got it to work this way https://github.com/gavofyork/entropretty/pull/18 using [livereload](https://www.npmjs.com/package/livereload#method-2-add-code-to-page)
