### ISSUE TITLE
how to load an html page ?

### ISSUE THREAD

**Issue by kavikaran** [zeit/serve#272]
hello,

Thank you for your very helpful awesome-micro modules.while developing micro services i need to load html page in response of service.For example, In express node-js framework We can give public folder route in response of api. 

Is there any way to load public folder on particular route or in response of particular service ?

I hope you got my issue.Thanks in advance.

```
const { send,buffer,text,json,createError } = require('micro')
const { router,get,post,options } = require('microrouter')
const cors = require('micro-cors')()

const docs = cors(async(req, res) => {
  sendFile('public/index.html');
})

const notfound = cors((req, res) => send(res, 200,"route not found"))

module.exports = router(
  get('/docs', docs),
  options('/*', notfound)
)
```

**Comment by leo** [comment]
`serve` doesn't yet provide a middleware - issue [here](https://github.com/zeit/serve/issues/267) 😊
