### ISSUE TITLE
Feature - proxying / server-side injection of sensitive keys?

### ISSUE THREAD

**Issue by gcloeval** [zeit/serve#280]
Currently using this with now.sh static deployments for our react app, working well, thank you!

We need to call some third party APIs with sensitive keys, are there any possibilities to do that?

Something like described here:
https://www.npmjs.com/package/express-request-proxy

**Comment by leo** [comment]
https://zeit.co/docs/getting-started/secrets

**Comment by gcloeval** [comment]
Thank you for prompt response.

Could you please clarify - arent these still going to be exposed to anyone with the developer console / watching network requests - they will eventually see something like http://googleapi/translate?key=1234

Cheers

**Comment by leo** [comment]
If you include them as GET parameters, yes... 🙈 Depending on where you need to send your secrets, you need to make sure establish an encrypted connection by yourself. `serve` it not related to that.

**Comment by gcloeval** [comment]
well i mean get, post, custom auth headers, SSL or not, it seems that an end-user of any SPA hosted via serve as part of static now.sh deployment offering would end up being able to see sensitive information via simple dev-tools console... feels kinda like a limitation to me. thats why we were aksing if we could somehow proxy through and do senstive stuff as part of the server.
but i understand if serve was not designed for that purpose, so we will investigate alternative approaches
