### ISSUE TITLE
Ignore option can't match wildcards

### ISSUE THREAD

**Issue by nzambello** [zeit/serve#281]
I discovered using `serve` that `ignore` option can match only exact file names.
So I forked the repo and I played with this: I'd like to use wildcards, too.
I'd like to use the meta-character `*` as I would use it in bash, to ignore every .js file passing "\*.js" or to ignore any file whose name begins by 'A' passing "A*\".

I'm submitting a PR with my work: #307.

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply use the `rewrites` option to rewrite paths you'd like to ignore to your 404 route.
