### ISSUE TITLE
Use image SVG icon for files that are being served as images (.gif, .jpg, .png, .svg)

### ISSUE THREAD

**Issue by tohjustin** [zeit/serve#285]
From the designs found in https://github.com/zeit/art/blob/master/serve/look.sketch
<img width="1392" alt="sketch-preview" src="https://user-images.githubusercontent.com/8844886/32138910-a349c9cc-bbf0-11e7-9075-569e35445307.png">

Currently `serve` uses the same icons for files & images, would be great if we have a different icon for images (similar to the one shown in the screenshot above).

**Comment by leo** [comment]
https://github.com/zeit/serve/pull/286
