### ISSUE TITLE
Parent directory not sorted correctly

### ISSUE THREAD

**Issue by tohjustin** [zeit/serve#287]
**Current behavior**
- Parent directory isn't the first entry in the file list
![current-behavior](https://user-images.githubusercontent.com/8844886/32141019-0575dec4-bc32-11e7-910c-5c0def592357.png)

**Expected behavior**
- Parent directory is the first entry in the file list, aligns with the convention in [Apache](https://www.tecmint.com/wp-content/uploads/2017/01/Apache-Directory-Listing.png) & [Nginx](https://www.linickx.com/files/2015/02/df_nginx_autoindex.png)
![expected-behavior](https://user-images.githubusercontent.com/8844886/32141004-75153884-bc31-11e7-80e1-f77937ad91d1.png)

**Comment by leo** [comment]
Closed in https://github.com/zeit/serve/pull/288
