### ISSUE TITLE
When embedded in my app the home page works but everything else returns Not Found

### ISSUE THREAD

**Issue by skywickenden** [zeit/serve#290]
I've embedded serve in `server.js`

    const serve = require('serve');

    const server = serve('build', {
      port: 5000,
      ignore: ['node_modules']
    });

If I then run this with `node server.js` Then all appears to be working on the home page using `localhost:5000`, but if I navigate to any other page on the site then it returns a `Not Found` error

If I run `serve -s build` from the command line then everything works fine.

This is being used to serve a very simple [React Create App](https://github.com/facebookincubator/create-react-app)

**Comment by tohjustin** [comment]
I think your app's client-side routing isn't working because you're missing a flag:
```javascript
const serve = require('serve');

serve('dist', {
  port: 2000,
  ignore: ['node_modules'],
  single: true, // <-- for serving SPA's
});
```

Here's the list of options available in serve:
```bash
❯ serve -help
The option "l" is unknown. Here's a list of all available options:

  Usage: serve [options] [command]

  Commands:

    help  Display help

  Options:

    -a, --auth      Serve behind basic auth
    -c, --cache     Time in milliseconds for caching files in the browser
    -n, --clipless  Don't copy address to clipboard (disabled by default)
    -C, --cors      Setup * CORS headers to allow requests from any origin (disabled by default)
    -h, --help      Output usage information
    -i, --ignore    Files and directories to ignore
    -o, --open      Open local address in browser (disabled by default)
    -p, --port <n>  Port to listen on (defaults to 5000)
    -S, --silent    Don't log anything to the console
    -s, --single    Serve single page applications (sets `-c` to 1 day)
    -T, --ssl       Serve content using SSL (disabled by default)
    -t, --treeless  Don't display statics tree (disabled by default)
    -u, --unzipped  Disable GZIP compression
    -v, --version   Output the version number
```

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `rewrites` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).
