### ISSUE TITLE
Clipboard: opt-in rather than opt-out

### ISSUE THREAD

**Issue by ivangreene** [zeit/serve#292]
Automatically overwriting a user's clipboard is an extremely intrusive action for a piece of software to take. When it happens on the web without me expecting it, I liken it to scrolljacking.

I think this feature would be better as an opt-in flag, rather than the default.

If that's not going to change, then please at least mention it in the main `readme.md`. Nowhere to be found until you run the command for help.

**Comment by leo** [comment]
The clipboard is now gone. If the community agrees to want it back, we can add it again!

For now, we decided it's okay to drop it.

Please read the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

**Comment by marcvangend** [comment]
Obviously not many people care (otherwise this thread would have been longer) but I wholeheartedly agree with the OP. The community wanted the nice looking message back (#424) but the (automatic, opt-out) clipboard wasn't mentioned once in that issue. Just my 2 cents.

**Comment by jorisw** [comment]
Agree, I found the clipboard feature to be very disruptive while developing. Frankly, modifying the clipboard should _always_ be an explicit action by the user. Otherwise it's potentially unchecked dataloss. You'll probably find this in most operating system guidelines.
