### ISSUE TITLE
[Feature] Set default extension to .html for static routing

### ISSUE THREAD

**Issue by itaditya** [zeit/serve#294]
Citing to issue #293 

Many projects use static html files for handling routing.
Eg -  http://localhost:5000/main, it must render the main.html file.

Many serving utilities have this feature.
https://github.com/indexzero/http-server/
http://surge.sh/

Lack of this feature is the main reason I'm still using http-server and not serve. 

I can contribute to buidling this

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

**Comment by itaditya** [comment]
That's great @leo . I'll look into it
