### ISSUE TITLE
Listen to a path (IPC) instead of a port

### ISSUE THREAD

**Issue by izeau** [zeit/serve#295]
Would you be open to a pull request to implement [listening to a path](https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections) instead of a port?

E.g. `serve --socket /tmp/mysocket.sock`

One possible use case would be continuous delivery:

  0. have a reverse proxy rule to proxy `https://cd.domain.tld/<group>/<user>/<commit>/<path>` to `/tmp/cd.<group>.<user>.<commit>.sock` with a `/<path>` request URI
  0. build static assets
  0. use `serve --socket /tmp/cd.<group>.<user>.<commit>.sock` to serve the assets

Please tell me if you’re interested.

**Comment by izeau** [comment]
Currently implemented at [rednetio/serve](https://github.com/rednetio/serve) with a `--path` (or `-P` for short) parameter

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by passing `--listen`. As described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0), it's now a completely fresh start for this project. You can run `--help` to see what's possible.
