### ISSUE TITLE
Using serve programmatically via API does not respect cors option

### ISSUE THREAD

**Issue by aversini** [zeit/serve#296]
I tried to use `serve` in my application via its API. It's working fine expect for the `cors` option.
It looks like it's being ignored because of [this line](https://github.com/zeit/serve/blob/05e386c598b7fb58025ff0469977b1ca13057d31/lib/api.js#L10) in `lib/api.js`.

Here is my code:

```js
const serve = require('serve')
const server = serve(process.cwd(), {
  port: 8080,
  cors: true
})
```

Thanks!

**Comment by just-boris** [comment]
There actually was a bug. I have submitted a PR with the fix: https://github.com/zeit/serve/pull/309
