### ISSUE TITLE
Can't stop serve with ctrl+c in windows10 cmd

### ISSUE THREAD

**Issue by TamasHuang** [zeit/serve#297]
I‘m a new guy to learn react.js.  when i build a app, then  `serve -s build`, then i use `Ctrl+C`,but it can't stop the serve.  also can visit my app use "http://localhost:5000"

**Comment by Gua-naiko-che** [comment]
I just tried this with Powershell and Windows Command Prompt and `Ctrl+C` works as expected in my machine:
![imagen](https://user-images.githubusercontent.com/6260564/33285973-45575f06-d3b4-11e7-94b1-1997fc4e77aa.png)

After doing this, I can't access the app anymore at "http://localhost:5000"

Can you give more details about this issue?

**Comment by marcoc1712** [comment]
I have the same problem,  also if you choose to teminate the batch still run and if I restart my machine it startup again, so "http://localhost:5000" is always accesible form the first serve command on and no way to stop it.

**Comment by bodaz** [comment]
I'm having the same issue on Mac as well. From `create-react-app`, I did `yarn build` then `serve -s build`, but then even if I `ctrl+c` or restart the machine, http://localhost:5000/ is still accessible with the app running

**Comment by marcoc1712** [comment]
After some trials I think node.js (or don't know what) is serving on localhost:5000 also withou run serve command (and also without install serve at all).

Very unclear...

**Comment by bodaz** [comment]
found the reason: it's because the service workers are running in the background.  

Once I unregistered the service workers from the Dev Tools(Application -> Service Workers), the ports are back to normal

**Comment by blinkcat** [comment]
so, how to stop the app from the terminal?

**Comment by leo** [comment]
This should now be working with the latest version!

Thank you for the effort you've put into this!

Please also read the details about the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).
