### ISSUE TITLE
Disable /service-worker.js and /sw.js caching in SPA mode?

### ISSUE THREAD

**Issue by jeffposnick** [zeit/serve#299]
Similar to how `index.html` is exempted from caching when in SPA mode, would you be open to explicitly exempting `/sw.js` and `/service-worker.js` from being cached?

There's no guarantee that a service worker file is going to be named `/sw.js` or `/service-worker.js`, but those are definitely the two most common names, and that matches what `create-react-app` outputs.

Some context:
- https://stackoverflow.com/questions/38843970/service-worker-javascript-update-frequency-every-24-hours/38854905#38854905
- https://github.com/facebookincubator/create-react-app/issues/3516
- https://github.com/zeit/serve/issues/268

**Comment by praveenweb** [comment]
Can serve accept a config file where i can specify caching rules for different assets? In that way, it won't be opinionated.

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `headers` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).

By default, no caching headers are applied.
