### ISSUE TITLE
Https support not usable yet

### ISSUE THREAD

**Issue by akuji1993** [zeit/serve#300]
This commit https://github.com/zeit/serve/commit/c6336eaf184feeda7699a541f02bed2d74eabe14 implemented the support for HTTPS, but upgrading to 6.4.1 I still can't see the added ssl option on the man page, where it should be. 

Using `serve -ssl` also doesn't work, tried different things, couldn't reverse engineer what works.

**Comment by laggingreflex** [comment]
Is this still an issue? Also multi-character flags require double hyphens: `--ssl`

**Comment by Diolor** [comment]
Running `serve --ssl`will force https and but with a [self signed cert](https://github.com/zeit/serve/blob/master/bin/serve.js#L16).

The feature to setup a custom cert doesn't exist

**Comment by akuji1993** [comment]
I honestly don't know how I solved this, but I can see the ssl command now. You can close this I guess.
