### ISSUE TITLE
Using serve within Docker and Create React App 

### ISSUE THREAD

**Issue by FahdW** [zeit/serve#302]
Using serve in docker with create react app, has rendered the ports i used to for them to be unusable. It is constantly running on that port even after a restart, and killing the docker container. So i am wondering how do you use serve and how do you switch it off is there no kill command?

**Comment by topleft** [comment]
+1

**Comment by topleft** [comment]
after running `docker run -it --rm -p 5000:5000 --name react-demo react-docker` with `CMD serve -s build` in my Dockerfile I cannot stop the process running on port 5000.

docker ps show no container because I ran the --rm command, but I think somehow serve is still running.

any ideas? thanks

**Comment by topleft** [comment]
found it, I needed to kill the service worker via chrome

--> chrome://serviceworker-internals/ --> unregister the work on the port in question

**Comment by leo** [comment]
👍

**Comment by toritsejuFO** [comment]
Thank you very much, battled with this for over a day. Had to be swticing ports just to continue working and be sure of my changes that I had so many open.

> found it, I needed to kill the service worker via chrome
> 
> --> chrome://serviceworker-internals/ --> unregister the work on the port in question
