### ISSUE TITLE
Proposal: designating non-redirecting routes for SPAs

### ISSUE THREAD

**Issue by fritz-c** [zeit/serve#306]
I'm using what I believe is a normal-enough stack; `create-react-app` for the frontend, `serve` for hosting as an SPA, placed behind a DNS that performs server-side caching of JS files. There are multiple servers hosting the build behind a load balancer.

This setup works fine until deployment, at which point a rollout or unfortunate timing for a page reload could result in a user receiving the new HTML and trying to access the new file from a yet-to-be-updated server. The result is that `mysite.com/static/js/main.d7378dda.js` redirects to the base `index.html` and is cached by the DNS. This means that subsequent requests for that file will return HTML content as the JS script. This causes problems.

I propose a flag to use in combination with the `-s` flag, which would allow you to designate files that should be excluded from the redirection behavior applied to the rest of the app. I would be willing to implement this. Is there interest in merging such a feature?

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `rewrites` or `redirects` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).
