### ISSUE TITLE
How to serve in the background as a demon.

### ISSUE THREAD

**Issue by sarfrazarshad** [zeit/serve#308]
Hi I want to use serve for production however when ever I run it using 
serve -s build
it is killed whenever I close the terminal or press ctrl-c.

**Comment by tohjustin** [comment]
I'm pretty sure that there are better ways than this but you can run it as a background process (see here information: https://kb.iu.edu/d/afnz):

```bash
serve -s build &
```

You also might want to redirect `stdout` & `stderr` into a separate file for logging.

**Comment by pablopunk** [comment]
@sarfrazarshad You can use something like `screen` or `tmux` to keep the session open. Also, take a look at [pm2](https://github.com/Unitech/pm2), you can do a lot of things with it.

**Comment by leo** [comment]
☝️ Exactly.

Or create a Node.js child process to fork it into the background. But this is definitely not something that `serve` needs to support - i hope you understand.

**Comment by burtontanner** [comment]
@pablopunk do you know how I could run "serve . --single -p 4000" but with pm2?

**Comment by pablopunk** [comment]
@burtontanner what's the problem with that?

**Comment by burtontanner** [comment]
@pablopunk I was wanting to do something like "pm2 start 'serve --single -p 4000'". I ended up creating a bash script (serve.sh) that contained 'serve . --single -p 4000'. Then I could run 'pm2 start serve.sh'.

**Comment by burtontanner** [comment]
Ahh I didn't think of that. Thanks @pablopunk
