### ISSUE TITLE
npm i -g serve error because of timed-out dependency

### ISSUE THREAD

**Issue by exztinct01** [zeit/serve#310]
C:\Users\Admin>npm i -g serve
    npm ERR! code ENOVERSIONS
    npm ERR! No valid versions available for timed-out

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-01-06T19_42_36_726Z-debug.log`

**Comment by Fallion** [comment]
Global issue. Author seems to have removed it from npm.

**Comment by leo** [comment]
We haven‘t removed any of our packages. npm recently had an issue where they lost several packages - you can see more details on their sites. :)
