### ISSUE TITLE
500 error in a directory with symlinks

### ISSUE THREAD

**Issue by darthdeus** [zeit/serve#317]
Running `serve` in my home directory and accessing localhost:5000 fails with

```
Error: ENOENT: no such file or directory, stat '/Users/darth/.ackrc
```

Even though that path is valid, and the file is a working symlink.

**Comment by paulogdm** [comment]
Same here! Maybe a redirect should be done by serve?

**Comment by paulogdm** [comment]
Got it working here after changing some permissions on the symlink!

**Comment by leo** [comment]
Yea, I don't think we support symlinks. Should we? 🤔 

Why would you place a symlink in something that you're sharing on the web?

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `redirects` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).
