### ISSUE TITLE
Serving API documentation of a "micro" microservice

### ISSUE THREAD

**Issue by martosoler** [zeit/serve#318]
Hi,

I'm looking for advice on how can use serve to display a fancy web page with the API documentation (which internally its a Swagger specification).

What I don't understand is if I can have both, the microservice and this running together in a different port or maybe a different endpoint.

Thanks

**Comment by paulogdm** [comment]
I'm using [ReDoc](https://github.com/Rebilly/ReDoc) and it works like a charm with `serve`. And yes, if you're in your local machine and in the same server simply use `serve` in another port. With `now`, however, you need to work with `micro-proxy` and `now alias`, so it is not a big thing really...

**Comment by martosoler** [comment]
Thanks for the recommendation, it works perfectly !!
