### ISSUE TITLE
Custom CORS headers

### ISSUE THREAD

**Issue by JonWallsten** [zeit/serve#319]
I need to set a specific origin instead of a wildcard for _Access-Control-Allow-Origin_.
So I would like to request a feature where you can specify these either as a flag or in a separate config/.serverc file. I'm not sure my node skills are could enough to create a PR unfortunately.

```
Failed to load http://localhost:3010/appentries.json: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:4000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by ajwhite** [comment]
Use `-C` or `--cors=true` 

https://github.com/zeit/serve/blob/297748b59a4d730e59e6e423ab655b683e220a40/lib/options.js#L30-L34

**Comment by JonWallsten** [comment]
@ajwhite Sorry for being rude, but did you even read my question? Setting _cors_ to _true_ adds a * (wildcard) to _Access-Control-Allow-Origin_ which is not allowed when credentials mode set to 'include'. You need to set the specific domain. We however removed serve and went with express.js instead for the flexibility needed.

**Comment by crhistianramirez** [comment]
For anyone else looking you can set custom headers by creating a serve.json and setting the properties as defined here: https://github.com/zeit/serve-handler#options

**Comment by josh-may** [comment]
@crhistianramirez Mind explaining this a bit further? Where is this code added?

**Comment by crhistianramirez** [comment]
I probably should have linked [this instead](https://vercel.com/docs/concepts/edge-network/headers#custom-response-headers) looks like you create the serve.json file in the /public folder. This guy has an example of what that [file might look like ](https://github.com/vercel/serve/issues/670)

Hope that helps, I don't remember posting my original answer 😅
