### ISSUE TITLE
Graceful Shutdown

### ISSUE THREAD

**Issue by nickhudkins** [zeit/serve#320]
I really like the simplicity of `serve` and I have no other needs (at the moment) so it fits the bill very nicely.

The one thing that would be nice is if it had the ability to do a graceful shutdown (Hi Rolling Deploys!). Is this something that would be considered to include in the library? I plan on building it for myself, but didn't know if @rauchg and co believed it would make sense as part of this library or its own project.

**Comment by leo** [comment]
What do you mean by that? Wait until all sockets are closed?

**Comment by nickhudkins** [comment]
Stop accepting new connections, and let any existing request finish. (X Seconds after the SIGINT or SIGTERM is sent, a SIGKILL will terminate the process.) If you had any requests that were taking that long to complete, those connections would be destroyed.

**Comment by nickhudkins** [comment]
It looks like I may already have my answer over here: https://github.com/zeit/micro/issues/304

**Comment by leo** [comment]
We're invoking `micro` programmatically, so that's not covered. But yes, `serve` should do the exact same in my opinion. 👍

**Comment by nickhudkins** [comment]
Seems reasonable!
