### ISSUE TITLE
No way to serve on localhost only

### ISSUE THREAD

**Issue by xrisk** [zeit/serve#325]

**Comment by paulogdm** [comment]
This doesnt make any sense at all. Can you please explain?

**Comment by xrisk** [comment]
If I type `serve`, then my files get served to anybody on my network, whereas I want it to be only served on localhost. 

There is no way to do this judging from the output from `serve --help`. Ideally, `serve` would accept an address to bind on, instead of simply binding to `0.0.0.0`.

**Comment by leo** [comment]
Great catch, we should definitely have a flag for that! 👍 

```
serve --local
```

or 

```
serve --only-local
```

(I think the first one is better).

And then it only listens on `localhost` instead of `0.0.0.0`.

**Comment by xrisk** [comment]
It might be better to accept an address to bind on, instead of arbitrarily constraining the user between a choice of `0.0.0.0` / `localhost`. 

A particular machine could have more than 1 IP address for instance. You should be able to serve on once of those IPs without affecting the other.

**Comment by leo** [comment]
Closed in https://github.com/zeit/serve/pull/327#pullrequestreview-99129079
