### ISSUE TITLE
ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by edgaryp** [zeit/serve#329]
I was able to install **serve** at initial **create-react-app** environment but not on this project. Couldn't figure out what would cause the problem. Any help would be appreciated.

![screen shot](https://user-images.githubusercontent.com/22573884/36243384-5d1831c4-1275-11e8-9564-c0aef5a345be.jpg)

**Comment by leo** [comment]
This is an error related to npm, not serve. 🙏
