### ISSUE TITLE
Feature request: Replace environment files inside files.

### ISSUE THREAD

**Issue by francocorreasosa** [zeit/serve#333]
I have a use case that `serve` can solve without breaking it's original purpose.

I may have an `index.html` file with some variables I'd like to replace when serving it.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script src="https://cdn.example.com/app/v1/bundle.js"></script>
    <script>
        App.initialize({ foo: #SERVE_ENV['BAR'] })
    </script>
</body>
</html>
```

I'd like to replace `#SERVE_ENV['BAR']` with the environment variable `BAR`.

Let me know what you think guys :)
Thanks!

**Comment by leo** [comment]
The only possible way to do this without decreasing the performance of `serve` would be to replace the variables on build time, so that's what I suggest you do. 😊 

Otherwise: Thanks for the effort you've put into this.
