### ISSUE TITLE
Multiple directories

### ISSUE THREAD

**Issue by edencorbin** [zeit/serve#334]
Any way, on a single serve instance, to serve multiple directories. IE /public and /otherassets as an example, without serving all the folders/files in a common parent directory that contains them both? Thanks

**Comment by leo** [comment]
You'd have to run `serve` twice for this, once for each directory. Otherwise they would both be available under the same port, which means under the same parent directory, speaking in terms of the path within the browser.

**Comment by 4cm4k1** [comment]
@edencorbin I would suggest using the `concurrently` npm package to run two instances at the same time. 😁
