### ISSUE TITLE
Two serve instances and cors not working

### ISSUE THREAD

**Issue by edencorbin** [zeit/serve#335]
I am getting No 'Access-Control-Allow-Origin' header is present on the requested resource. when running the following code and requesting an assetServer file from an application served by server.

```
const serve = require('serve')

const server = serve(__dirname+"/build", {
  port: 5000,
  single: true,
  cors: true
})

const assetServer = serve(__dirname+"/assets", {
  port: 5001,
  cors: true
})
```

Can this be accomplished and is my configuration not correct?

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `headers` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).
