### ISSUE TITLE
How to combine SPA with robots.txt

### ISSUE THREAD

**Issue by mavame** [zeit/serve#337]
I have the need to host a single-page app but publish a `robots.txt` file at the application root. I use:

`serve -s build`

To serve my site out of my `build` directory, at which `robots.txt` lives. But I can't navigate to http://mysiteurl/robots.txt. I just get served up my app's 404 page. I'm using `create-react-app` by the way.

Can you point me in the right direction?

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `headers` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).
