### ISSUE TITLE
Is it possible to serve React app that is under development?

### ISSUE THREAD

**Issue by Levelleor** [zeit/serve#343]
When I serve I get a list of directories from the folder I serve from. I am here from React Git page since they mention this as an alternative to Chrome's extension. I am sorry I am a newbie in this but is it possible to serve React app without building it after every edit or I got that wrong? 

Thanks for attention anyway!

**Comment by zwik** [comment]
What exactly do you mean with "building" a react app?

If you have an HTML file and you let React hook to an element you can do that perfectly with serve, no problem.

**Comment by Levelleor** [comment]
> What exactly do you mean with "building" a react app?

`npm run build`

I was searching for hours and looks like the problem is that React isn't rendering my code to index.html in public. I have no idea how to make it write to HTML file in development mode. Maybe you have any ideas? So far only CDN links worked for me but they require to write code in the same HTML file, it can't be the only way of doing it...

**Comment by Levelleor** [comment]
Nevermind. Here is the solution. I needed to install Webpack and follow steps here: 

https://medium.com/@fastlane80/setup-react-js-with-npm-babel-6-and-webpack-in-under-1-hour-1a714f973506

Now Webpack bundles all the code in bundle.js which is connected to index.html so I can serve it. Perfect.
