### ISSUE TITLE
--ssl doesn't work on Chrome

### ISSUE THREAD

**Issue by corysimmons** [zeit/serve#344]
![image](https://user-images.githubusercontent.com/224636/37484716-b83a634c-285f-11e8-9338-3a5f935b8bc6.png)

openssl-self-signed-certificate is pretty old (last update to repo 2016)

I suspect Chrome disabled that particular certificates options https://www.chromestatus.com/feature/4981025180483584

https://github.com/neverendingqs/openssl-self-signed-certificate/blob/master/index.js is literally nothing.

Would Zeit (trusted) be interested in maintaining a simple/modern localhost cert for the dev community?

**Comment by Ashot-KR** [comment]
Little lifehack: open `chrome://flags/#allow-insecure-localhost` and set `enabled`.
With this option enabled chrome will not show error page for `https://localhost`

**Comment by corysimmons** [comment]
Nice thanks @Ashot-KR

**Comment by leo** [comment]
We decided to drop this feature from the core for now, as there a simply too many variants to support and there should be some form of load balancer or proxy on top of `serve` on your server, which takes care of this (and compression, for example).
