### ISSUE TITLE
404 Not Found: detect-port@1.2.2

### ISSUE THREAD

**Issue by psi-4ward** [zeit/serve#350]
```
npm info using npm@5.6.0
npm info using node@v8.11.1
...
npm ERR! code E404
npm ERR! 404 Not Found: detect-port@1.2.2
```

Seems theres no `1.2.2`of [detect-port](https://github.com/node-modules/detect-port/tags)

**Comment by stripedpajamas** [comment]
It does have a version 1.2.2 - npm says it was published about 5 months ago. I don't think they updated their releases on Github though. 

https://www.npmjs.com/package/detect-port (versions tab)

And `npm install detect-port@1.2.2` doesn't fail using the same version of node+npm. Maybe a local registry issue?

**Comment by psi-4ward** [comment]
Absolutly correct, cache/nexus problem.

Thx for that hint!
