### ISSUE TITLE
"--cache" option values need to be documented.

### ISSUE THREAD

**Issue by preston** [zeit/serve#358]
It looks like a value of "0" will disable browser caching, but it doesn't appear to be documented anywhere. :)

 https://github.com/zeit/serve/blob/e1a4fb7592e7d8e12e1f54d5b918fae050ff5235/lib/server.js#L111

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `headers` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).
