### ISSUE TITLE
Can't set CORS headers

### ISSUE THREAD

**Issue by slorber** [zeit/serve#36]
I'm using list/ns to serve my single-page-appication assets (js/css...)

Unfortunatly, the index.html page of my SPA is not a static asset that is in the static deployment: it is a dynamic html page generated by my backend server which is hosted on another domain.

I'd like to set a CORS header, so that my index.html page, served from another domain, is able to load JS assets from the list/ns deployment.

It would be nice to have an option to set custom headers, and a shortcut --cors (like http-server) would also be convenient. Thanks ;)

**Comment by joeyvandijk** [comment]
The reference issue #37 contains the cors setting, but the current `index.js` is missing the execution code for the CORS option. Please copy & fix it, while apparantly some merge removed it from the code, so the CORS-option is currently non-existent.

Or am I missing something while `cors` is provided in the help section, but nothing is done with that flag.

**Comment by leo** [comment]
`--cors` is [now usable](https://github.com/zeit/serve/releases/tag/3.2.9)!
