### ISSUE TITLE
-T does not enable SSL, unlike --ssl

### ISSUE THREAD

**Issue by nickmccurdy** [zeit/serve#361]
When I run `serve -T build`, the root path displays a directory listing instead of `index.html`. This appears to be a bug with the flag alias because `serve --ssl build` works as expected.

**Comment by leo** [comment]
We've decided to not support SSL as a core feature anymore - in all cases there should be some form of proxy or load balancer on top to handle SSL, as there are simply too many variants.

I hope you understand!

Please also read the details about the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).
