### ISSUE TITLE
Force use port

### ISSUE THREAD

**Issue by kazzkiq** [zeit/serve#365]
Is there a way to force serve to use a port, and if its already being used, it just throws?

The behavior of simply picking another port may be troublesome in some cases, like when you have other things depending on this first server listening on the right port.

An example of this is using `micro-proxy` with `serve`, if I configure my proxy to forward requests to port `5000`, but suddenly `serve` decided it was a good idea to pick another port without halting/throwing, it may lead to odd behavior and hard to catch bugs, because I'm basically listening the wrong server.

**Comment by jespertheend** [comment]
@leo  Is this still the case? I'm on 11.3.0 but I'm still getting a message that a different port is used.

**Comment by jespertheend** [comment]
https://github.com/zeit/serve/pull/490 👀

**Comment by pskelin** [comment]
Can we please get an npm version with this feature? It would be great to use it directly from npm instead of referencing github urls.
Thanks!
