### ISSUE TITLE
UPDATE CHECK FAILED

### ISSUE THREAD

**Issue by sant123** [zeit/serve#367]
![image](https://user-images.githubusercontent.com/7959437/40041043-5209b62e-57e2-11e8-989c-dd94481184ad.png)

Also when pressing Ctrl + C the process terminates after some seconds. 

For now I'm using version 6.5.6.

Thank you!

**Comment by sant123** [comment]
![image](https://user-images.githubusercontent.com/7959437/40041291-0fcbaf14-57e3-11e8-8ea5-c01c7d00a8ed.png)

For some reason, everything is now working as expected with latest version, however the `Timeout` below can make some weird behavior with Ctrl + C command. 

Maybe you can review it @leo. For now feel free to close it.

**Comment by leo** [comment]
The timeout was introduced in https://github.com/zeit/serve/pull/360 to ensure serve can start even if there's an error with the update-checker. Glad it's working fine now.
