### ISSUE TITLE
Feature request: --open could accept as param the landing page

### ISSUE THREAD

**Issue by ghuser** [zeit/serve#368]
The landing page could be added as an optional param to `--open`

So the command below

    serve myapp --open main.html

will still serve `myapp/` directory, but will open the browser in `http://localhost:5000/main.html`

**Comment by leo** [comment]
The command is neither copying to clipboard anymore, nor is it opening anything. Many people have found this disturbing, so we removed it in the latest release.

I hope you understand. 🙏 

Thank you for the effort you've put into this!

Please also read the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).
