### ISSUE TITLE
CRA message should be deprecated

### ISSUE THREAD

**Issue by sulliwane** [zeit/serve#379]
This is what Create React App suggest after running `npm run build`:
```
The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

http://bit.ly/2vY88Kr
```
This is deprecated since V7, as the new api is not compatible at all with previous versions.

I will cross post to CRA github, but I think it's also related to this package somehow. maybe you should consider tagging the V7 `@next` instead of `@latest`...

**Comment by nickmccurdy** [comment]
v7 is the latest stable release. Everything looks fine from Serve's end, we should update CRA's docs and CLI.

**Comment by nickmccurdy** [comment]
https://github.com/facebook/create-react-app/pull/4532

**Comment by sulliwane** [comment]
Ok, thanks for the feedback

**Comment by gaearon** [comment]
This is very frustrating on our side.

We didn’t add Serve instructions to CRA ourselves. We took a PR from Zeit team. Of course at the time we assumed we can rely on the arguments not changing.

Now all CRA apps have non-working hardcoded instructions.

**Comment by sulliwane** [comment]
My sentiment exactly, as that's what happened to me on a production environment and it took me at least 30 minutes to realize and fix the problem

**Comment by leo** [comment]
@sulliwane This is now solved, as per [this comment](https://github.com/zeit/serve/issues/382#issuecomment-392735123). Sorry!
