### ISSUE TITLE
ERROR: URL is not defined

### ISSUE THREAD

**Issue by gdereese** [zeit/serve#380]
When running the following command on v7.0.1 of the package:
`serve --listen tcp://127.0.0.1:1234`
the following error is logged to the console and the program terminates:
`ERROR: URL is not defined`

This is in context of a package running in Node 8.11.2.

**Comment by jaeseok-park** [comment]
I have the same issue.

**Comment by jaeseok-park** [comment]
Temporarily, I added a line in bin/serve.js.

```
#!/usr/bin/env node

// Native
const http = require('http');
const path = require('path');
const fs = require('fs');
const {promisify} = require('util');
const {URL} = require('url');             // This is the added line.
```

**Comment by leo** [comment]
Fixed in https://github.com/zeit/serve/pull/381
