### ISSUE TITLE
Please add back support for -s option for the sake of CRA users

### ISSUE THREAD

**Issue by gaearon** [zeit/serve#382]
Hi 👋 

As you might know, Serve is currently featured in production build instructions of every single app created with CRA. We didn’t add it to CRA ourselves—we took a PR from @leo (https://github.com/facebook/create-react-app/pull/1760). It’s a nice tool indeed! Zeit is doing a lot of important work in the React ecosystem, and at the time I thought it would be a nice gesture to recommend it too.

When we took that PR we assumed that `serve` is a simple utility that wouldn’t change in important ways for such a simple (from the user’s point of view) use case as serving a single static folder for an SPA.

However, this changed with Serve 7. Specifically, the `-s` option was dropped. This means that every single app made with CRA now prints wrong instructions: https://github.com/zeit/serve/issues/379.

Now I agree that normally it would be our fault for including an instruction in the build output without specifying the version. But again, **we didn’t add `serve` ourselves to CRA**. We took a PR from the Zeit team (https://github.com/facebook/create-react-app/pull/1760). That PR didn’t include a version number so I thought there was an implicit assumption this part of the Serve API isn’t going to change.

This is ultimately my fault for relying on something external in the instructions. But the current situation is deeply confusing to our users, and I hope you can help. Quoting https://github.com/zeit/serve/issues/379:

>My sentiment exactly, as that's what happened to me on a production environment and it took me at least 30 minutes to realize and fix the problem

There are several possible solutions.

We could take https://github.com/facebook/create-react-app/pull/4532. Note this is neither simple nor exhaustive. It means I would have to drop everything I’m doing, and release patch releases for every major version of `react-dev-utils` that contains this text.

This still wouldn’t be sufficient either because, as you can see in https://github.com/facebook/create-react-app/pull/1760 (which is where the instructions were added for the first time), they used to be a part of `react-scripts` itself! So there is just no possible way to release this change for people pinned to a specific `react-scripts` version. In practice it means that **all apps older than a certain version will keep printing wrong instructions**.

Our philosophy is that people shouldn’t feel obligated to upgrade their toolchains, and it is sad that their projects will now be confusing to everyone who runs them. This includes both apps and open source examples and demos through which people learn React.

And of course, people who ejected before it was moved to `react-dev-utils` just **have that message *hardcoded* into their build scripts**. There is no way we could fix it.

Even if we take https://github.com/facebook/create-react-app/pull/4532, it seems like it does something different now (without `-s` the whole point of using `serve` is lost for us). [Using a config file](https://github.com/zeit/serve-handler#rewrites-array) is not an option for us, and is pretty much a showstopper for CRA. This has to be a simple single command.

So this means that we’ll not only have to do all the work above (and it will not be sufficient, as I explained, because many people will still see the old message), but also quickly find a maintained replacement before too many people get confused by their broken build testing instructions.

An alternative solution would be to keep `-s`. How complex would you estimate this to be?

If you’re convinced dropping it is best, is there any chance you could give us at least a few weeks to do those patch releases and do our best effort at updating the messages where it is possible? Maybe once we figure out another tool to migrate to, you could make `serve -s` print a message that also recommends it? At least this way old projects would still print something sensible.

To be clear, I’m not concerned for myself. This is just very unfortunate for our users and especially beginners who learn not to trust what their tools tell them.

**Comment by sjdweb** [comment]
Also, the -p option has been removed. This screwed our deployments this morning too.

**Comment by leo** [comment]
Just jumped on DM with @gaearon and we figured out a great solution. Sorry for the inconvenience we've caused. I will personally ensure that this won't happen again!

The [latest release](https://github.com/zeit/serve/releases/tag/7.1.0) of `serve` allows for `serve -s` and `serve --single`, which both apply the following rewrite preset:

```json
{
  "source": "**",
  "destination": "/index.html"
}
```

Effectively making CRA apps work just as before again.

For @sjdweb, we also have a solution: Please just pass `-l <port>` instead of `-p <port>`.

**Comment by gaearon** [comment]
Thanks 💜💜💜

**Comment by franciscop-invast** [comment]
For anyone coming here, I'd like to suggest the fix being different. We were manually installing `serve` and running it:

```
npm install serve
serve -s build -p 3000
```

Which just started causing the strange error `ERROR: Unknown or unexpected option: -s` with the code that was running just a day before.

The better way IMHO is to install `serve` as a dependency, so that the version is somewhat fixed with no breaking changes, and then run it as npm script:

```
"scripts": {
  "serve": "serve -s build -p 3000"
}
```

Then `npm run serve` will work in the same way in dev and prod. You could add the `@6` on the `npm install serve@6`, but then you'd have to make sure the versions are synced manually while I prefer to keep dev and prod versions the same in code.
