### ISSUE TITLE
Cors option?

### ISSUE THREAD

**Issue by jschr** [zeit/serve#389]
Hey, I use `serve` every day so thanks for the continued maintenance :-)

The latest update seems to have removed the cors option from the cli, was that intentional?

**Comment by leo** [comment]
Yes! 😊 

Please use the new `headers` option in `serve.json` to apply any CORS headers:

https://github.com/zeit/serve-handler#headers-array

**Comment by jschr** [comment]
Gotcha, thanks.

I will say this makes the tool less convenient for me as I use it to quickly serve up a local folder with `npx serve <dir> --cors`. With the CLI option I don't need to add any extra configuration specific to `serve` for each project.

Just my 2 cents though! I'm very likely in the minority of people who used `--cors` option frequently. 

My workaround for now is to just use the older version as it works perfectly fine for my use case `npx serve@6.5.8 --cors <dir>`

Cheers!

**Comment by johnwebbcole** [comment]
@jschr thanks for the work around!  👍  for adding the command line option back

**Comment by rofrol** [comment]
```bash
$ cat serve.json
{
  "headers": [
    { "source" : "**/*.@(jpg|jpeg|gif|png|txt)"
    , "headers" :
        [{ "key" : "Access-Control-Allow-Origin"
         , "value" : "*"
         }
        ,{ "key" : "Access-Control-Allow-Headers"
         , "value" : "Origin, X-Requested-With, Content-Type, Accept, Range"
         }
        ]
    }
  ]
}

$ serve
INFO: Discovered configuration in `serve.json`
INFO: Accepting connections at http://localhost:5000
```

**Comment by hsribei** [comment]
Still using `npx serve@6.5.8 --cors` for a quick way to use cors without creating a config file. I don't know if this is up for debate, but I'd love to have the `--cors` flag in the latest version.

**Comment by oncletom** [comment]
Yeah likewise, I don't get this craving for config files.

Thanks for pointing out `serve@6`.

**Comment by jschr** [comment]
Just thought I'd update this issue. I've been using https://github.com/indexzero/http-server instead now. 

This packaged worked great as as quick and easy CLI tool but seems to not be interested in that use case anymore.

**Comment by sebbean** [comment]
@jschr awesome thanks for suggesting a usable alternative!! 🙏🏽

**Comment by rofrol** [comment]
@sebbean And this is how you make it work with SPA navigation https://github.com/indexzero/http-server/issues/519#issuecomment-487614367

**Comment by trusktr** [comment]
`live-server` also does the trick (has a `--cors` option), and as a bonus can automatically refresh your web page on file changes if you specify `--watch` (or `--watch=patterns` to watch certain files).

**Comment by leo** [comment]
[It's back!](https://github.com/zeit/serve/releases/tag/11.3.0)

Thanks for the feedback.
