### ISSUE TITLE
304 caching does not work

### ISSUE THREAD

**Issue by slorber** [zeit/serve#40]
Here are 2 deployments with the same file:
- list: https://ns-oafyjpgsns.now.sh/first.txt
- http-server: https://ns-korbjpbazb.now.sh/content/first.txt

You can see that the http-server returns a 304 answer if you ask the file again, while the list implementation always returns 200 with content in any case.

https://github.com/zeit/list/blob/master/bin/list#L242

As far as I see in current implementation, you supply Etags in the answer but you never return 304 on Etag matches (maybe it's intentional and should be handled by now Nginx?), only on "if-modified-since" which is never sent because the server never sends a "last-modified" header.

I think list should support both caching systems, or at least only etags, and return 304 on etags match.

As source of inspiration, you can look at source code of file-server used on http-server that works fine for me
https://github.com/jfhbrook/node-ecstatic/blob/fe17a5623c18319f82101b6549e9e2e526e03d1f/lib/ecstatic.js#L284

(note there's a weak/strong etag subtility, not really sure to understand how it works)

I would be happy to submit a PR if you tell me what kind of behavior you want to support

**Comment by leo** [comment]
Should be fixed in https://github.com/zeit/serve/releases/tag/3.1.0

**Comment by slorber** [comment]
Thanks @leo I don't have time to check now but will certainly give a feedback on this later

**Comment by leo** [comment]
@slorber Great! 😊
