### ISSUE TITLE
Cannot open normal htmls file with '-s' option

### ISSUE THREAD

**Issue by jaeseok-park** [zeit/serve#404]
Hi.

I'm using `serve` to develop and test SPA, so I run it with `-s` option.
However, when I use `-s`, it seems not to support normal html files.

My directory to open has `index.html` for SPA and a normal html file for documentation.
But when I open the normal html file, it seems to be redirected another path.

Could you check it, please?

**Comment by denkristoffer** [comment]
The default config uses `cleanUrls` for filenames ending in `.html`. Have you tried disabling it? https://github.com/zeit/serve-handler#cleanurls-booleanarray

**Comment by leo** [comment]
Exactly. Please do it like @denkristoffer suggested and disable the option (or pass an array to only allow the feature on certain paths)... 😊

**Comment by jaeseok-park** [comment]
Thank you @danielking and @leo .
After using `serve.json`, I can often my doc.html file.

By the way, I have an issue related this.
When I open `http://localhost:3000/doc.html`, sometimes `doc.html` does not open well.
At that time, chrome dev-tool shows different behaviors.

< Good case >
![doc html](https://user-images.githubusercontent.com/8565274/41080888-8252eff6-6a63-11e8-9066-77991e02315b.png)

< Bad case >
![service-worker](https://user-images.githubusercontent.com/8565274/41080891-875b2658-6a63-11e8-9a5f-8ffe51bcf4f2.png)

My build folder which I use with `serve` has `service-worker.js` file. (I guess it is produced by react.)
I guess it makes this situation.

How can I see `doc.html` all the time?

**Comment by abelosorio** [comment]
I'm facing this same problem but using `serve` in the command line:

```
serve -s build
```

Is there any way to override this option using the command line?

**Comment by abelosorio** [comment]
I agree with @donmccurdy (https://github.com/zeit/serve/issues/401#issuecomment-394890378) that `cleanUrls` should be `false` by default, and you should provide a `--no-clean-urls` (or similar) option for command line.

Also, I couldn't find any documentation at all about using `serve` in the command line.

**Comment by jaeseok-park** [comment]
Thank you for your advice, @abelosorio .

I already used `cleanUrls: false` with `serve.json` file in my build directory.
```json
{
  "cleanUrls": false
}
```
The message from my execution shows it applied well.
```
$ serve -s -l 3001 build
INFO: Discovered configuration in `serve.json`
INFO: Accepting connections at http://localhost:3001
```
But, this issue still occurs.

**Comment by abelosorio** [comment]
Hi @jaeseok-park, that's weird. I've used the same workaround and it worked for me...

**Comment by abelosorio** [comment]
Hi @leo, would you please review this issue?

As you can read above I fixed the issue using the `serve.json` file with the `cleanUrls: false` option, but @jaeseok-park reported the same workaround with different results.

Thanks in advance
