### ISSUE TITLE
I'm missing ip info

### ISSUE THREAD

**Issue by CanRau** [zeit/serve#409]
Hey guys, thanks for the great work!
since 7 it feels faster and even though content is still reachable by ip address within the local network it's not being shown anymore which I'm missing as my ip address changes from time to time so i have to look it up to test my projects on mobile and other machines
any chance we could get it "back" or should i make a little wrapper for my use case? or any other suggestions?

e.g. `accepting connections at http://192.168.0.16:3000`

greets

**Comment by leo** [comment]
I think we'll add it back to the output, just in a more minimalistic way 👍

**Comment by CanRau** [comment]
awesome..i'm satisfied 💯 :D
