### ISSUE TITLE
What happened to serve cli?

### ISSUE THREAD

**Issue by bitinn** [zeit/serve#414]
Hi,

I am not trying to sound alarming, but it seems A LOT as changed recently (since last time I opened an issue in February #330), and `serve` didn't have a changelog to reflect this at all.

It took me a while to figure out [7.0.0](https://github.com/zeit/serve/releases/tag/7.0.0) basically wipe every existing conventions, and current readme doesn't mention you need to stick with `6.5.8`.

IMO, 7.0.0 release makes a previous simple cli much more complex, even with `serve --help`. To illustrate my problem, here is my full attempts at 7.x after install (as a 6.x user):

```
dev@g3:~/www/test$ sudo serve -p 80 ~/www/test/
ERROR: Unknown or unexpected option: -p
dev@g3:~/www/test$ sudo serve -h

  serve - Static file serving and directory listing

  USAGE

      $ serve --help
      $ serve --version
      $ serve [-l listen_uri [-l ...]] [directory]

      By default, serve will listen on 0.0.0.0:3000 and serve the
      current working directory on that address.

      Specifying a single --listen argument will overwrite the default, not supplement it.

  OPTIONS

      --help                              Shows this help message

      -v, --version                       Displays the current version of serve

      -l, --listen listen_uri             Specify a URI endpoint on which to listen (see below) -
                                          more than one may be specified to listen in multiple places

      -d, --debug                         Show debugging information

      -s, --single                        Rewrite all not-found requests to `index.html`

  ENDPOINTS

      Listen endpoints (specified by the --listen or -l options above) instruct serve
      to listen on one or more interfaces/ports, UNIX domain sockets, or Windows named pipes.

      For TCP ports on hostname "localhost":

          $ serve -l 1234

      For TCP (traditional host/port) endpoints:

          $ serve -l tcp://hostname:1234

      For UNIX domain socket endpoints:

          $ serve -l unix:/path/to/socket.sock

      For Windows named pipe endpoints:

          $ serve -l pipe:\\.\pipe\PipeName

dev@g3:~/www/test$ sudo serve -l 80 ~/www/test/
INFO: Accepting connections at http://localhost:80
^C
INFO: Gracefully shutting down. Please wait...
dev@g3:~/www/test$ serve -l 80 ~/www/test/
serve: Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1338:19)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at startEndpoint (/usr/lib/node_modules/serve/bin/serve.js:152:19)
    at /usr/lib/node_modules/serve/bin/serve.js:303:3
    at <anonymous>

INFO: Gracefully shutting down. Please wait...
dev@g3:~/www/test$ sudo serve -l 80 ~/www/test/
INFO: Accepting connections at http://localhost:80
^C
INFO: Gracefully shutting down. Please wait...
dev@g3:~/www/test$ sudo serve -l tcp://0.0.0.0:80 ~/www/test/
INFO: Accepting connections at http://0.0.0.0:80
^C
INFO: Gracefully shutting down. Please wait...
```

All I want was to do a simple `sudo serve -p 80 ~/www/test/` (listen on 0.0.0.0:80 or server_ip:80).

Yes, I could downgrade to 6.x, but I think there might be better ways to guide old users.

Love,
David

**Comment by wawhal** [comment]
`-p` is no more a valid argument.

You have to use `-l` instead to mention the port number.

**Comment by bitinn** [comment]
@wawhal You are missing the point, `-l 80` doesn't work the same way as `-p 80`.

**Comment by leo** [comment]
@bitinn I'm sorry for any inconvenience we've caused, but yes - we indeed released many breaking changes in the latest version, which is why it was a [major release](https://semver.org/#summary).

With this release, we've modeled `serve` after [micro](https://github.com/zeit/micro) and made it much more accessible to proffesional use, while retaining almost the same simplicity as before and making the core much more slim.

We've concluded that we cannot maintain many of the options that were added over the years, as they simply aren't supposed to be part of the core of such a project. They're normally to be handled by a much higher layer, like a webserver (compression, SSL, auth, etc).

You can read more [here](https://zeit.co/blog/serve-7). Also `-l <port>` DOES work. 😊
