### ISSUE TITLE
how to serve index.html by default?

### ISSUE THREAD

**Issue by andyburke** [zeit/serve#417]
I can't seem to get index.html to be served if it exists in a directory. Is there a rewrite I need to use? If so, might I suggest adding it to the README.md? This is a pretty common use case.

**Comment by leo** [comment]
Working perfectly fine:

![image](https://user-images.githubusercontent.com/6170607/41291731-ca7c03a8-6e50-11e8-9f66-0a3d557aefae.png)

![image](https://user-images.githubusercontent.com/6170607/41291738-cfc2e4da-6e50-11e8-9fe8-b2c39dabc02e.png)

It seems like your directory structure is somehow not right. Please check!

**Comment by andyburke** [comment]
I am using the "public" option to serve a subdirectory. Perhaps that's causing the issue?

**Comment by andyburke** [comment]
Hmm, trying to repro and having difficulty. Will keep trying to understand what's happening in this case.

**Comment by andyburke** [comment]
Ok, the issue is that my "public" folder has a dot in the name, I'll open a new issue.

**Comment by jjperezaguinaga** [comment]
@andyburke did you ever open the issue? just wasted half an hour due the same problem

**Comment by andyburke** [comment]
@jjperezaguinaga yes, PR was submitted and accepted.

@leo what version did the fix end up landing in?
