### ISSUE TITLE
File named 'index.html' is never found

### ISSUE THREAD

**Issue by TomMarius** [zeit/serve#420]
As the title goes, URL pointing to a file named 'index.html' is always redirected to root (that shows directory listing), and returns 404 if directory listing is disabled. This behaviour is new, and I assume incorrect. If the file is 'index.htm', I'm able to point at it, but it's not used as default page.

**Comment by leo** [comment]
@TomMarius Please set `cleanUrls` to `false` if you want to disable the default behavior of stripping this extension from file paths or making the index redirect.
