### ISSUE TITLE
What are the breaking changes?

### ISSUE THREAD

**Issue by Antonio-Laguna** [zeit/serve#422]
Hey @leo ,

I've been looking at the releases and I see 7.0.0 and 8.0.0 which are major changes from 6.x.x. I'm keen to update it but not sure which are the breaking changes I should be aware of.

Could you let me know or point me to where they are?

Thanks!

**Comment by leo** [comment]
I suggest comparting the output of `npx serve@6.5.8 help` to `npx serve@latest -h` to understand what has changed exactly. Also read [this](https://github.com/zeit/serve/releases/tag/7.0.0) and [this](https://zeit.co/blog/serve-7) if you have time.
