### ISSUE TITLE
check for update: skip for production deployments, implement timeout

### ISSUE THREAD

**Issue by patrikbeno** [zeit/serve#423]
all of this looks OK before #374 was introduced.

Timeout was introduced in #360 and update check was skipped entirely in production.

Now it's all back to naive and potentially breaking implementation.

serve@8.2.0

**Comment by leo** [comment]
The update check is happening behind a [catch](https://github.com/zeit/serve/blob/master/bin/serve.js#L32-L39) statement. It's not possible for it to crash the program.

**Comment by patrikbeno** [comment]
Following is possible:
- hang during startup while waiting for connection
- print irrelevant warnings during startup, e.g. SSL failure
- delay startup while performing irrelevant update check

I consider this a bug, because I cannot prevent any of this.

At least consider a `--no-update-check` option

**Comment by leo** [comment]
There is a [timeout](https://github.com/zeit/update-check/pull/9) in place, so that cannot happen

**Comment by patrikbeno** [comment]
@leo, it is irrevant if you are not interested in any kind of update check. In production, for example.
All I ask for is the option to disable the update check. I am interested in `serve` feature, not `update`, especially in production environment.

Of course, update check is useful, I don't dispute that, especially during development, but in production deployments, all it does is useless and out of context.

**Comment by patrikbeno** [comment]
@davemorrissey, in my case, I run it in docker, and I was able to short-circuit the whole process by following:

```
# dummy registry effectivelly disables update check and avoids irrelevant connection errors and startup delays
RUN echo "registry=http://localhost" > .npmrc
ENV NODE_ENV="production"
# /etc/hosts entry avoids DNS lookup delays and errors when resolving self hostname
CMD printf "127.0.0.1 $(hostname)" >> /etc/hosts && serve -l ${PORT:-80} -s
```
