### ISSUE TITLE
Regressions in DX for CRA users

### ISSUE THREAD

**Issue by gaearon** [zeit/serve#424]
We recommend using `serve` to test production builds locally in CRA.
There are a few things I noticed in the latest releases that regress the development experience:

* The default port changed from 5000 to 3000. This affects us a lot because *our* default development port is 3000. So now people can't run both DEV and PROD builds on default ports without having to change one of them. This is pretty inconvenient. It can also be confusing because CRA sets a service worker on the PROD build by default. So now you get a production service worker in development next time. We try to solve this situation on CRA side by always overriding it in DEV but you can see how this can be confusing. Changing the default port to 5000 (or literally anything other than 3000) would solve this DX regression.

* The output is no longer delightful.

Compare before:

<img width="672" alt="screen shot 2018-06-13 at 6 06 34 pm" src="https://user-images.githubusercontent.com/810438/41367250-643d0808-6f36-11e8-85b7-b6922a787ba7.png">

and after: 

<img width="584" alt="screen shot 2018-06-13 at 6 06 16 pm" src="https://user-images.githubusercontent.com/810438/41367249-64242fb8-6f36-11e8-979b-4fe536ff481b.png">

I know this is deeply subjective but.. the former looks like a *delightful* tool that cares about me, presents important information in a digestible way, and tries to anticipate my needs. It feels like a "brand", in the same sense as Jest watcher UI does. The latter looks like a bland generic server of which there are hundreds on npm.

Now again, I know this is deeply subjective, but this delightful experience is exactly what attracted me to  `serve` in the first place, and why I agreed to adding it to CRA build instructions. Maybe it's not the focus of the project anymore (which seems now focused on production use cases), and I could publish a fork that just aliases to `serve@6`, but I miss this.

Perhaps there could be a special minimalistic production mode, but without compromises to DX?
Thanks.

**Comment by leo** [comment]
About to implement this. Just btw, @gaearon: There's no need to run `serve .`, just run `serve`.

**Comment by leo** [comment]
This just landed! 🎉 

- [Brought back the old message](https://github.com/zeit/serve/pull/429)
- [Revert the default port to 5000](https://github.com/zeit/serve/pull/427)

I'm closing it, as it's now on master - going out with the next major release.

I might wait a little bit to collect more changes for 9.0.0, but it's definitely going out in the next few days.

**Comment by gaearon** [comment]
Thank you!

**Comment by leo** [comment]
[Out now!](https://github.com/zeit/serve/releases/tag/9.0.0
