### ISSUE TITLE
Feature: --open Option?

### ISSUE THREAD

**Issue by kennedyrose** [zeit/serve#425]
Any way we could get an option to open http://localhost:{port}/ in the default browser? I've been using `static-server` since it supports this option, but I'd rather use `serve` if possible.

**Comment by sant123** [comment]
This feature was present in previous versions, ¿what happened?

**Comment by elboletaire** [comment]
Yup, I've ended here because I've just updated serve.. and some of my dev scripts started failing because now there's no `-o` option :confused:

**Comment by sant123** [comment]
@leo may you review this issue, please?

**Comment by kennedyrose** [comment]
I've submit a [pull request](https://github.com/zeit/serve/pull/454) for this feature.

**Comment by Telokis** [comment]
This PR seems nice. I'd like to have this feature! ❤️

**Comment by loopmode** [comment]
So currently, we can not specify the port at all using this module?

**Comment by FDiskas** [comment]
We can downgrade to `"serve": "6.5.2",`

**Comment by gkatsev** [comment]
Looks like this is due the rewrite of 7.0: https://github.com/zeit/serve/pull/374
It seems like the purpose of this project changed at that point as well. It's a lot more powerful now but to get a lot of the same features that previously existed you need to create a new config file and configure things. I think this is a huge step back from what was available in v6.
I've downgraded back down to v6 but I hope a lot of the features that were available by default back then would be re-added for the simplicity and ease-of-use it had previously.

**Comment by gluons** [comment]
This feature is very useful.  
Why @zeit remove it?

@kennedyrose 's PR (#454) is closed. 🙄

Will we get this feature back?  
Please bring back the `-o`. 😥

**Comment by cniesen** [comment]
> 
> 
> This feature is very useful.
> Why @zeit remove it?
> 
> @kennedyrose 's PR (#454) is closed. 🙄
> 
> Will we get this feature back?
> Please bring back the `-o`. 😥

It's documented in the #454 as to why the feature will not be incorporated. 
Feature creep and added dependencies.  Makes sense.  Look at this stack exchange for alternatives:
https://stackoverflow.com/questions/40713752/how-to-open-browser-to-localhost-through-npm-scripts/41267691#41267691
