### ISSUE TITLE
What version of serve is now running?

### ISSUE THREAD

**Issue by andyburke** [zeit/serve#436]
Tried to deploy a static site that would work as expected under 9.1.0 (fixed 'public' setting with with dots in it), but am getting a directory listing.

Is there a way to find out what version of serve zeit is running for static deployments?

When can I expect 9.x to hit?

**Comment by leo** [comment]
Now is not running `serve` at all. It's running 3.2.0 of [serve-handler](https://github.com/zeit/serve-handler). One second, I'm bumping it!

**Comment by leo** [comment]
One second, I'm bumping it!

**Comment by leo** [comment]
Done!

**Comment by andyburke** [comment]
Thanks!
