### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND <my hostname>

### ISSUE THREAD

**Issue by wolverian** [zeit/serve#437]
~~~bash
src% mkdir tmp
src% cd tmp
tmp% echo "Hello, world!" > index.html
tmp% serve
(node:39744) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND flower
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
(node:39744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
INFO: Gracefully shutting down. Please wait...
tmp% hostname
flower
tmp% nslookup `hostname`
Server:		10.245.22.6
Address:	10.245.22.6#53

** server can't find flower: NXDOMAIN
tmp% serve --version
9.1.0
~~~

**Comment by RafalWilinski** [comment]
I'm also experiencing this issue. Using node `v8.11.1` and serve `9.1.0`.

**Comment by luisrudge** [comment]
same here

**Comment by karbica** [comment]
+1

```js
{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.29.0',
  node: '8.11.2',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.54',
  zlib: '1.2.11' }
```

@kazzkiq I too wondered the same thing. I checked my global modules for what's outdated and saw that jump. Strange.

**Comment by jjperezaguinaga** [comment]
Same here, had to downgrade to `serve@8` to get it working. Got the warning about `9.1.0` though.

**Comment by ryanhamley** [comment]
The issue is [this line](https://github.com/zeit/serve/blob/master/bin/serve.js#L176) but the unhandled promise is masking an underlying issue where `dns.lookup(os.hostname())` is failing, at least on my local machine. 

I was able to fix the errors (again, at least on my local machine) by replacing line 176 with this:

```
const hostname = address === 'localhost' ? address : os.hostname();
const {address: ip} = await lookup(hostname)
.catch((err) => {
    console.error(error(`Not able to complete DNS lookup for ${hostname}: ${err.message}`));
    process.exit(1);
});
```

I'm not super familiar with this library or with what `os.hostname()` is supposed to be so I'm open to suggestions on whether or not this is an acceptable generalized solution.

**Comment by saadq** [comment]
I'm getting this issue in v10.0.2 as well. I just have a simple `example` directory that just has an `index.html` file in it:

```
example
└── index.html
```

When I run `serve .` the server works fine, but I get the following output:

```
ERROR: DNS lookup failed: getaddrinfo ENOTFOUND squadri
```

<img width="1440" alt="screen shot 2018-09-28 at 3 53 21 pm" src="https://user-images.githubusercontent.com/5678694/46230570-0045eb80-c337-11e8-9bcd-d51835b18f5a.png">

**Comment by j0nd0n7** [comment]
Same issue with node v10.13.0 and serve 10.1.1.
Any progress on this?
