### ISSUE TITLE
Can this serve on relative path?

### ISSUE THREAD

**Issue by chris-fa** [zeit/serve#440]
I want to serve not as the root, but at relative path: `http://localhost:5000/webapp`. Is this possible?

**Comment by leo** [comment]
Use the [rewrites](https://github.com/zeit/serve-handler#rewrites-array) property:

```
{
  "rewrites": [
    { "source": "/webapp/:rest", "destination": "/:rest" },
  ]
}
```

And then serve the directory of your choice.

**Comment by ccll** [comment]
@leo Tried your solution but that only works on `/webapp/foo` path, on a `/webapp/foo/bar` path it will 404, the `:rest` can only capture the text till next `/` delimiter.
Are there any way to capture a `/webapp/(.*)` pattern?
Thanks!

**Comment by ccll** [comment]
Can't find a solution so I replaced serve with express.js, which works great.
