### ISSUE TITLE
Support HTTP range requests

### ISSUE THREAD

**Issue by rexpan** [zeit/serve#447]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

Related #342

**Comment by mischnic** [comment]
👍

HTML5 video elements don't work in Safari without range request support

**Comment by jeremiahlee** [comment]
I think this may be related to a problem that I am having. [A video on my static site](https://www.jeremiahlee.com/blog/sup/2017/2017-10-10-pragmatic-design-with-json-api/slide-70.mp4) is not loading in Safari and Chrome.

The video loads fine in Firefox, but not Safari and Chrome. The differences that I can identify:

Firefox does not send a `range` request header. It receives a `200` response without a `Content-Length` header. The video plays to the amusement of people everywhere.

Safari sends a `Range: bytes=0-1` header in the request and receives a `206` response with `Content-Length: 2` and `Content-Range: bytes 0-1/2`. It logs a console error: `Failed to load resource: Plug-in handled load`.

Chrome sends 3 requests. Its first request looks like Firefox's. It then makes a 2nd request after receipt of the `200`. The second request is exactly like the first, but add `range: bytes=0-`. It gets a `206` response with `Content-Length: 2194624` and `Content-Range: bytes 0-2194623/2194624`. Chrome then makes a third request with the headers `if-range: W/"df5e28104932a6ef65e9c352919b66a04680f93c"` and `range: bytes=2162688-2194623` and gets a `416` response with now's 416 HTML error page.

Why isn't Zeit now serving my video correctly?

**Comment by leo** [comment]
This just landed in [9.5.0](https://github.com/zeit/serve/releases/tag/9.5.0)! 🎉
