### ISSUE TITLE
Couldn't find any versions for "serve" that matches "9.5.0"

### ISSUE THREAD

**Issue by ardalann** [zeit/serve#474]
First off, thank you for the awesome work in this package and your other packages 🙌 

Now the issue: We used to use serve@v9.5.0 on our project, but now we're getting not-found errors like the following:
```
error Couldn't find any versions for "serve" that matches "9.5.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
```
I looked at [the versions on npmjs](https://www.npmjs.com/package/serve) and noticed 9.5.0 has been removed. Could you please explain why? My concern is there may have been a critical vulnerability that we have been exposed to and that's the reason you've removed it.

**Comment by styfle** [comment]
We don't have the ability to unpublish from npm.

Typically, a package can only be unpublished in [72 hours](https://docs.npmjs.com/cli/unpublish) after it was published.

I don't see a tag nor a commit that bumped to 9.5.0 so perhaps it never existed.

https://github.com/zeit/serve/commits/master?after=f14e267672f730e496cdbb93fc91e6b52f6f4722+34
