### ISSUE TITLE
Silence update available message

### ISSUE THREAD

**Issue by kentcdodds** [zeit/serve#481]
I'm running serve `10.0.1` and I'm getting a message:

```
UPDATE AVAILABLE The latest version of `serve` is 10.0.2
```

I've been using `serve` for a long time and these constant messages to upgrade are super annoying. Could we have a way/flag to silence them please?

**Comment by leo** [comment]
Added in https://github.com/zeit/serve/pull/457.

**Comment by kentcdodds** [comment]
Any chance we could get an argument for this? Using an environment variable means that I'd have to use something like `cross-env` for my script to work for both... I'd be happy to open a PR to add a flag.
