### ISSUE TITLE
How can I get the pid of the process serve created?

### ISSUE THREAD

**Issue by AntiMoron** [zeit/serve#493]
As title.

**Comment by r0mflip** [comment]
In your shell if you run
``` bash
# & runs it in background
$ serve ./public &
```

You can use `echo $!` to get the pid.

In programmatic ways if you are using spawn on exec have a look at https://nodejs.org/api/child_process.html#child_process_subprocess_pid

**Comment by AntiMoron** [comment]
Thanks. Closing.
