### ISSUE TITLE
Serve not found

### ISSUE THREAD

**Issue by akhil-gautam** [zeit/serve#496]
```
No command 'serve' found, did you mean:
 Command 'pserve' from package 'python-pyramid' (universe)
 Command 'server' from package 'rsplib-legacy-wrappers' (universe)
serve: command not found
```
This is what is get when I run `serve -s build` .
I have installed it globally.

**Comment by imbarbudiman** [comment]
the same thing happened to me

**Comment by akhil-gautam** [comment]
@imbarbudiman 
I got it fixed by closing the terminal and reopening again. And then I installed it globally. Also make sure to create your builds. :laughing:

**Comment by zhongjingjogy** [comment]
Find it with `yarn global bin`.

**Comment by imbarbudiman** [comment]
heemmm ... I don't really remember why I asked here, haha
