### ISSUE TITLE
Issues setting config file (`serve.json`)

### ISSUE THREAD

**Issue by arel** [zeit/serve#498]
Just started using `serve` and it's great! But, I had a hard time figuring out how to configure it with a custom `serve.json` file. There were several contributing factors:

* Absolute paths to `serve.json` are not found.
    ```bash
    serve --config /app/serve.json build  # SILENTLY FAILS
    ```

    * This seems like a bug
    * At a minimum, this should be documented in the README, if it's intended behavior

* Config path is relative to the path being _served_ not the current working directory.
    * I would have expected the path relative to where the command was called.
    * At a minimum, this should be documented clearly in the README

* `serve` fails silently when `--config` is set but file is not found.
    * I would expect an error if the file is missing.
    * At minimum I would expect a warning (similar to when config file is found: `INFO Discovered configuration in ../serve.json`)

* Documentation does not clearly indicate how to set config file, or what a `serve.json` file looks like. An example would be helpful here.

**Comment by FlorianBurgevin** [comment]
+1

**Comment by jespertheend** [comment]
I was having a hard time figuring out how serve.json works as well. I didn't know the path was relative to the directory being served. It's working now. Thanks @arel!

**Comment by bensleveritt** [comment]
Being relative to the served directory really threw me too. Would be good to either have that documented, or just relative to the CWD.

**Comment by warren-bank** [comment]
simple fix.. please [patch](https://github.com/zeit/serve/tree/11.0.2/bin/serve.js#L249)

__current code__:

```javascript
const loadConfig = async (cwd, entry, args) => {
	const files = [
		'serve.json',
		'now.json',
		'package.json'
	];

	if (args['--config']) {
		files.unshift(args['--config']);
	}

	const config = {};

	for (const file of files) {
		const location = path.join(entry, file);
		//...
	}
	//...
}
```

__better methodology__:

```javascript
const loadConfig = async (cwd, entry, args) => {
	const files = [
		path.join(entry, 'serve.json'),
		path.join(entry, 'now.json'),
		path.join(entry, 'package.json')
	];

	if (args['--config']) {
		files.unshift(
			path.isAbsolute(args['--config'])
				? path.resolve(args['--config'])
				: path.join(entry, args['--config'])
		);
	}

	const config = {};

	for (const file of files) {
		// [line removed] const location = path.join(entry, file);
		//...
	}
	//...
}
```
