### ISSUE TITLE
react-router applications getting 404 error with version 10.1.2

### ISSUE THREAD

**Issue by joejustesen** [zeit/serve#507]
Create a CRA application with react-router.  Works fine with webpack development server, but production builds all get a 404 error with non-root urls running serve@10.1.2   Running serve@10.1.1 works fine.  Not sure what changed in the new version, but it seems to have broken SPA applications routing.

**Comment by ahce** [comment]
Same problem.
I think the cause is this [commit](https://github.com/zeit/serve-handler/commit/c212e2d431d4331f11ed49fe8e450b50181a4415)

**Comment by etoler1841** [comment]
Same issue here. All good before 10.1.2, now I get a 404 on all routes.

**Comment by nicolasparada** [comment]
Yeah, `single` mode is broken now.

**Comment by tryzniak** [comment]
Can't seem to reproduce this issue. Version of create-react-app is 2.1.5, react-router-dom ^4.3.1, serve 10.1.2

**Comment by ravagedsnail** [comment]
Likely same root cause for me, but getting 404's when using re-writes but not when hitting a resource directly.

serve.json
`
{
  "public": "dist",
  "rewrites": [
    {
      "source": "/app/:project/manifest.json",
      "destination": "/:project/manifest.json"
    }
  ]
}
`

In my dist folder I simply have a file /dist/web/manifest.json

When navigating to http://localhost:5000/app/web/manifest.json I receive a 404
When navigating to http://localhost:5000/web/manifest.json I receive the file.

**Comment by theluk** [comment]
same here, but 10.1.1 works fine

**Comment by scott-ho** [comment]
@AndyBitz could you fix the problem?

**Comment by Mikilll94** [comment]
Version 10.1.2. I am also getting 404 when I manually type a url.

**Comment by Mikilll94** [comment]
I also confirm that 10.1.1 works fine.

**Comment by woodreamz** [comment]
same issue with 10.1.2 (certainly caused by https://github.com/zeit/serve-handler/commit/c212e2d431d4331f11ed49fe8e450b50181a4415).

Issue is still there in 11.0.0.

Any update on this issue?

**Comment by mamiu** [comment]
As a workaround you can append **`-s .`** to your command until the bug is fixed.

So instead of just running

    serve

call

    serve -s .

**Comment by gambolputty** [comment]
Can confirm this behaviour:

```
rewrites: [
  { 'source': '**', 'destination': '/index.html' }
]
```

... gives me a 404 in version 11.0.0. In version 10.1.1 not.

**Comment by ahce** [comment]
Four months with this issue... 
Now the version 10.1.1 has this [vulnerability](https://www.npmjs.com/advisories/965)...

**Comment by leo** [comment]
A fix for this was released [today](https://github.com/zeit/serve/releases/tag/11.0.2). Can you confirm?

**Comment by ahce** [comment]
@leo fixed for me in version 11.0.2. Thanks!

**Comment by woodreamz** [comment]
@leo I confirm it is working in version 11.0.2. Thanks!

**Comment by AndyBitz** [comment]
👍

**Comment by PokimLee** [comment]
> I'm running serve@11.0.0 and it's working fine for me with the react-router-dom BrowserRouter in the production build.
> 
> And I also just use the single mode:
> 
> ```
> serve -s .
> ```

Thans so much! it works in V 11.2.0

**Comment by juanmartin** [comment]
I'm getting 404 when refreshing a react app using react-router. Running with -s flag, v11.3.2
Am I missing something?

**Comment by DallasP9124** [comment]
I am also having issue using react (built with vite however) using react-router. Exception for the root, all other routes produce a 404 even with rewrites.
I start with this command
```sh
serve \
-l 8443 \
client/dist \
--ssl-cert $SSL_CRT \
--ssl-key $SSL_KEY \
--ssl-pass ./k.pass

```
serve.json
```json
{
  "directoryListing": false,
  "cleanUrls": true,
  "rewrites": [{"source":  "**", "destination":  "/index.html"}]
}
```
