### ISSUE TITLE
Can the cors option be added back to the command line?

### ISSUE THREAD

**Issue by TrevorDev** [zeit/serve#510]
I'm happy to make the PR. The removal of this really broke my workflow of just running serve . -C and i can never remember what version had it when I need to install on a new PC.

Seems others had the same issue https://github.com/zeit/serve/issues/389 and use the older version due to this.

**Comment by jtotoole** [comment]
big +1 here!

**Comment by sebbean** [comment]
same!

**Comment by christ-off** [comment]
+1

**Comment by agentofuser** [comment]
@TrevorDev you're the hero we need 🦇

**Comment by sunanan** [comment]
+1

**Comment by agentofuser** [comment]
Found a better solution: https://www.yarnpkg.com/en/package/http-server

```
yarn global add http-server
hs --cors
```

**Comment by leo** [comment]
[It's back!](https://github.com/zeit/serve/releases/tag/11.3.0)

Thanks for the feedback.

**Comment by naivefun** [comment]
@leo  `--help` does not show `--cors` options yet in 11.3.0
