### ISSUE TITLE
SSL/TLS/HTTPS Support (yes, another one)

### ISSUE THREAD

**Issue by mattdodge** [zeit/serve#511]
I know there is already tons of discussion about HTTPS on here. I feel like most of the conversation is around "automatic" HTTPS though - obviously that is going to be a challenge with generating certs and trusting CAs and yadda yadda yadda.

Are we opposed to adding CLI flags to provide existing certs/keys to run with SSL though? There are a lot of tools popping up like [mkcert](https://github.com/FiloSottile/mkcert) and [cfssl](https://github.com/cloudflare/cfssl) that simplify the creation of local certs. There is also a recent trend of [requiring HTTPS](https://www.welivesecurity.com/2018/05/04/google-rolls-app-domain-built-https-tld/) on certain domain names. 

I can't imagine there would be opposition to this but perhaps I'm not fully understanding why HTTPS support isn't here in the first place. I'm happy to contribute and help, but want to make sure this is something the team is in support of first.

**Comment by csi-lk** [comment]
Cam to ask the same question, looks like support was implemented at some point with https://github.com/zeit/serve/pull/274 but I think the repo has evolved since then

**Comment by r0mflip** [comment]
> I can't imagine there would be opposition to this but perhaps I'm not fully understanding why HTTPS support isn't here in the first place.

`serve` is designed around the concept where your SSL is terminated by your reverse proxy, where your certs and all are managed by your organization rather by the developer (like on Zeit deployments).

**Comment by mattdodge** [comment]
@r0mflip you're speaking like you have authority to describe the intent of `serve` but I can't help but be skeptical. SSL termination? Reverse proxies? Those are things that exist in production, not development. Unless I'm completely misunderstanding what `serve`'s purpose is, it should rarely (never?) be run in production but rather on a developer's machine. I thought it existed to get a one-line command to view file directory and/or view a single page app.

If I had nginx up and running already why would I even need `serve`? This should be my replacement to a complicated nginx setup.

**Comment by r0mflip** [comment]
> @r0mflip you're speaking like you have authority to describe the intent of serve but I can't help but be skeptical.

@mattdodge That was never my intention, I clearly do not speak for `serve`. I've just given my opinion.

**Comment by EqualMa** [comment]
Currently, `--ssl-cert` and `--ssl-key`  options can be specified to enable ssl, as `serve --help` describes.
I tried it with [mkcert](https://github.com/FiloSottile/mkcert) and it works.
So maybe this issue can be closed now.

**Comment by mattdodge** [comment]
Yep you're right, didn't realize this was still open, thanks for the heads up!

**Comment by baharalidurrani** [comment]
Please add this to the docs too.
