### ISSUE TITLE
What tool did you use to create the screenshot?

### ISSUE THREAD

**Issue by searchy2** [zeit/serve#514]
This screenshot looks really good. Can I ask what tool you used to make it?
<img width="1122" alt="40541195-167ff460-601b-11e8-8f66-3b0c7ff96cbb" src="https://user-images.githubusercontent.com/19896174/54716766-8859c080-4b24-11e9-9d6a-8229e53e857f.png">
Thanks :fire:

**Comment by iam-medvedev** [comment]
This is built-in macOS screenshot tool (⌘ + shift + 4, then press space bar)

**Comment by searchy2** [comment]
Whoa! That is so cool! Thanks for sharing :) :tada: 

Do you know how to get that nice drop shadow with drag to screenshot? Instead of capturing a window, just a portion of a window.

**Comment by kognise** [comment]
@searchy2 First press Cmd-Shift-4, then press the spacebar. Then just click on a window,
