### ISSUE TITLE
--single option is broken since 10.1.2

### ISSUE THREAD

**Issue by spawnia** [zeit/serve#525]
As mentioned in https://github.com/zeit/serve/issues/506 the breakage must have occured when going from `10.1.1` to `10.1.2`.

I was trying to use the `--single` option with version `11.1.0` of this package and kept getting 404's. Downgrading to `10.1.1` did the trick.

**Comment by tomasbruckner** [comment]
Same issue - Windows 10 with Create React App 3. Downgrading also worked for me.

**Comment by cedx** [comment]
Same issue here: Node.js 12.3.0, Windows 10, `serve` 11.0.0.

**Comment by Noxxys** [comment]
Same problem here, I also noticed that adding a rewrite to `serve.json` doesn't have any effect.
```json
{
  "rewrites": [
    { "source": "/**", "destination": "/index.html" }
  ]
}
```
Serve finds my config file, but when I refresh a page of my Angular application, I get a 404 page instead of being sent to index.html.

**Comment by joeldenning** [comment]
Here's the commit that broke things for Windows: https://github.com/zeit/serve-handler/pull/76

**Comment by joeldenning** [comment]
Just submitted a PR that fixes this - https://github.com/zeit/serve-handler/pull/89

**Comment by leo** [comment]
A fix for this was released [today](https://github.com/zeit/serve/releases/tag/11.0.2).

**Comment by XCifer** [comment]
I had this problem and fixed by build localy on my laptop and upload build to my server. Usually I do build on my server (is it a wrong way?)

**Comment by comadaihiep92** [comment]
Thanks, working with it 👯
