### ISSUE TITLE
Add support for `no-redirect-index` option, because it can break pages with relative links (e.g. javadoc)

### ISSUE THREAD

**Issue by ghuser** [zeit/serve#528]
I've generated javadoc using `jdk11` and then performed the following:

    cd target/site/
    serve

When I try to access: 

`http://localhost:5000/apidocs/index.html`   
I get redirected to  
`http://localhost:5000/apidocs`  
which serves `index.html` content. 

But the page uses relative css path, which generates a request to `http://localhost:5000/stylesheet.css` 
 instead of `http://localhost:5000/apidocs/stylesheet.css`. 

This breaks the page.

When I place the same files under apache, the generated javadoc is displayed correctly because the redirection does not occur.

Actually I discovered this by trying to generate the full java site using `mvn site`. The generated site had a link to javadocs, which when clicked a redirection occurred to the no-css page.

**Comment by ghuser** [comment]
Using the option below in `serve.json` fixes the issues: 

    {
      "cleanUrls": false
    }

**Comment by Jack-Works** [comment]
How can I disable this behavior with no config file and not using bash? Just a single flag will be nice

**Comment by peabnuts123** [comment]
:+1: Any simple config available in `serve.json` should be exposed as command-line parameters too
