### ISSUE TITLE
serve is ignoring the current directory, serving disk root instead

### ISSUE THREAD

**Issue by chase-moskal** [zeit/serve#540]
hello friends

i've whipped up a debian linode instance, and i'm trying to use `serve` for development purposes to serve some static files

```bash
#!/usr/bin/env bash

PROJECT=${1?"first arg 'project' is required"}
PORT=${2?"second arg 'port' is required"}

cd ~/public/$PROJECT

echo "PWD! $PWD"

forever start $(which serve) -l $PORT

echo "serving $PROJECT on port $PORT..."
```

the problem is that serve is serving my linode's root directory, at `/` — so i see /etc/ and /bin/ and everything else

my script has the `echo "PWD! $PWD"` line just to verify that the current directory is indeed set correctly

`serve --help` tells me that `By default, serve will listen on 0.0.0.0:5000 and serve the current working directory on that address.`

so by default, serve will serve the current directory. this appears to not be working, and so, how do i override this default and specify the exact directory to be served?

maybe i'm just using unix wrong?

thanks in advanced, cheers! :wave:

**Comment by chase-moskal** [comment]
as a temporary solution, i switched to `http-server` which allows me to set the server root

i changed this line

```bash
forever start $(which serve) -l $PORT
```

into this line

```bash
forever start $(which http-server) -p $PORT ~/public/$PROJECT
```

and i got the results i was looking for

i originally switched from `http-server` to `serve` because of the security audit problems that `http-server` had a while back, and also, i prefer serve's directory listings :sunglasses: 

let me know if/how i can switch back, cheers :wave:

**Comment by aulisius** [comment]
Hi,

Can you try this? `serve` accepts server root as an argument.

```sh
forever start $(which serve) -l $PORT ~/public/$PROJECT
```

**Comment by chase-moskal** [comment]
oahp, there it is — i'm just a dummy and am also bad at reading `--help` :laughing: 

this solved my problem! thanks @aulisius!

```bash
forever start $(which serve) -l $PORT ~/public/$PROJECT
```

it would be kind of cool if an example to the readme could be added that makes this usage pattern abundantly clear -- maybe there's even a chance that somebody else out there is equally negligent with their attention as myself

cheers and thanks!

:wave: Chase
