### ISSUE TITLE
Add Brotli support

### ISSUE THREAD

**Issue by totsteps** [zeit/serve#543]
Since `Brotli` support is merged in node-12, is it possible to add support for it?

For reference:
https://github.com/nodejs/node/issues/18964 and https://github.com/nodejs/node/pull/24938#issuecomment-451689150

**Comment by styfle** [comment]
Hi @totsteps  

The `serve` cli is not intended to use for production applications.

Instead you can deploy your application to [ZEIT Now](https://zeit.co) by connecting your Git Repository in couple clicks.  Then each time you `git push` it will deploy!

You get Brotli, Gzip, and many other [features](https://zeit.co/docs/v2/network/compression) automatically.

Try this: https://zeit.co/import/git
