### ISSUE TITLE
[JSON] Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by MasterDavodXL** [zeit/serve#547]
I hope you can help me.

I spent a long time searching the internet to fix it but nothing was the same or work for me.

**I get a certificate error that can not be fixed.**

**I get it when creating a Bot for discord**. Here are some screenshots to see:

![imagen-1 VSCode](https://user-images.githubusercontent.com/53099452/61566371-36965800-aa7c-11e9-91a5-9f1304315fd6.png)

![Imagen-2 CMD](https://user-images.githubusercontent.com/53099452/61566377-3dbd6600-aa7c-11e9-92b8-ebeccc2218ea.png)

I hope you help me with this problem.

¡Thanks!

**Comment by styfle** [comment]
This error doesn't look like its coming from `serve`.
