### ISSUE TITLE
Setting Access-Control-Allow-Origin header in response

### ISSUE THREAD

**Issue by Tusshu** [zeit/serve#551]
I have created following file and placed in same directory where index.html file exists. 
`{
    "headers": [
      {
        "source" : "/./",
        "headers" : [{
          "key" : "Access-Control-Allow-Origin",
          "value" : "*"
        }]
      }
    ]
  }`
But I get the following message:
No 'Access-Control-Allow-Origin' header is present on the requested resource.

Do you see anything wrong in the above  configuration?
Thanks.

**Comment by jsejcksn** [comment]
See: https://zeit.co/docs/v2/advanced/routes/#headers

Use the header name as the key and the value as the value.
