### ISSUE TITLE
Add ability to sort by different metrics in the web UI

### ISSUE THREAD

**Issue by NightMachinary** [zeit/serve#553]
A sort by date modified is especially useful.

**Comment by styfle** [comment]
I think you might have created an issue in the wrong repo. There is no Web UI. This is a CLI.

**Comment by NightMachinary** [comment]
@styfle The CLI creates a http server serving the files. I like that server’s frontend to offer sorting by date modified.

**Comment by styfle** [comment]
I see, sounds like a duplicate of #574

**Comment by NightMachinary** [comment]
@styfle Not really. Custom CSS is a much lower level feature than just having the ability to sort the files by their modification date.
