### ISSUE TITLE
Hi, serve.json where can I configure it? Is there a reference code?

### ISSUE THREAD

**Issue by qiqingfu** [zeit/serve#567]
The dist directory generated after my Vue project was built, and I can use serve-handler to mount a static server, accessible online.

However, some interface reported 404 error, I would like some configuration, can be normal access to interface data.

How do I configure this

#### My directory structure looks like this:

```
  - dist
 - node_modules
 - index.js
 - package.json
```

#### I configured it like this, and the interface access is still 404

index.js

```javascript
const handler = require('serve-handler')
const http = require('http')

const server = http.createServer((req, res) => {
  return handler(req, res, {
    cleanUrls: false,
    public: './dist',
    rewrites: [
      {'source': 'disuseGoods/*', 'destination': '/index.html'}
    ],
    // redirects: [
    //   {'source': '/vm/', 'destination': 'http://10.30.94.44:11067:80'}
    // ]
    proxy: [
      {'path': '/vm/common/getColumns', 'destination': 'http://10.20.14.44:13067:80/vm/common/getColumns'}
    ]
  })
})

server.listen(80, 'vbase.dianxiaohuo.cn', () => {
  console.log('http://vbase.haoyunlai.cn:80')
```

**Comment by nemanjamilosavljevic-newtron** [comment]
So, @qiqingfu, why have you closed this? Could you provide your solution here, at least? Thanks!
