### ISSUE TITLE
How to get source IP address in RequestListener?

### ISSUE THREAD

**Issue by l3ender** [zeit/serve#573]
How do I get the IP address of the client in a `RequestListener`?

```js
const server = http.createServer((request, response) => {
	// let ipAddress = request.???
	return handler(request, response);
});
```

Thanks!

**Comment by carlos-menezes** [comment]
`request.connection` returns a net.Socket objects, which contains a property named `remoteAddress`. If you want to get the remote IP address of a client, you can write this:

```js
const server = http.createServer((request, response) => {
	const ipAddress = request.connection.remoteAddress;
	return handler(request, response);
});
```

[Read More](https://nodejs.org/api/net.html#net_socket_remoteaddress)
