### ISSUE TITLE
Custom CSS for directory listing

### ISSUE THREAD

**Issue by 3x** [zeit/serve#574]
Is there a way to customize the static file directory with CSS? I was unable to find this feature, if it exists.

Thanks for the awesome tool, Zeit! :heart:

**Comment by styfle** [comment]
This sounds like a duplicate of #532

**Comment by zyp001a** [comment]
> Is there a way to customize the static file directory with CSS? I was unable to find this feature, if it exists.
> 
> Thanks for the awesome tool, Zeit! ❤️

use some code like this to modifiy css: 
```
perl -pli.bak -e 's/white-space: nowrap;//' ~/.config/yarn/global/node_modules/serve-handler/src/directory.js
```
