### ISSUE TITLE
install on server with no Internet

### ISSUE THREAD

**Issue by ashkank83** [zeit/serve#577]
I need to install Serve on a server where there is no Internet access. Is there a tar file which I can use with all dependencies included? or do you recommend another way to do this? (I have NPM and node already installed on the server)

Thanks

**Comment by r0mflip** [comment]
Try cloning this repo. Install all dependencies. Copy the folder to your server and then use `npm link` on your server.

**Comment by ashkank83** [comment]
thanks will try
