### ISSUE TITLE
can this  lib be used in production?

### ISSUE THREAD

**Issue by njleonzhang** [zeit/serve#581]
I have all my static resources  (js/css/iamge/font) on cdn, and just want to host entry html (`index.html`) on my own server, can I use this lib in production if the daily PV is about 30 million?

**Comment by TeijiW** [comment]
I'll do a test with this lib to production, maybe I post here my results about this.
My application it's made with React and gonna have few accesses

**Comment by styfle** [comment]
Hi @njleonzhang  

The `serve` cli is not intended to use for production applications.

Instead you can deploy to [ZEIT Now](https://zeit.co) by connecting your Git Repository in couple clicks.  Then each time you `git push` it will deploy!

You get HTTP2, TLS, Brotli, and many other features automatically.

Try this: https://zeit.co/import/git

**Comment by njleonzhang** [comment]
Tnx for your answer

**Comment by nemanjamilosavljevic-newtron** [comment]
@styfle could you please expand on that answer as to why the `serve cli` should not be used in production?
