### ISSUE TITLE
Bad upgrade path from TJ’s serve

### ISSUE THREAD

**Issue by yuchi** [zeit/serve#59]
Hallo!

Nice to see `serve` is having a new function! *But* I see stuff breaking because I expected it to just be a new version of the package, which is not.

Could you at least give some information if someone is trying to render Jade files and similar that this is not *that* `serve`?

**Comment by derhuerst** [comment]
To make it clear: You're talking about [*that* `serve`](https://github.com/tj/serve)?

**Comment by yuchi** [comment]
That docs still say it is called `serve` on npm!

**Comment by derhuerst** [comment]
```shell
npm info serve@1.4.0 author
# TJ Holowaychuk <tj@vision-media.ca>
```

```shell
npm info serve@2.0.0 author
# leo
```

[`serve@1.4.0` – tj/serve](https://github.com/tj/serve/blob/a696aa4/package.json)
[`serve@2.0.0` – this repo](https://github.com/zeit/serve/blob/baf434cf0e3e38bf2104f451f516875cb0cd81df/package.json)

**Comment by derhuerst** [comment]
This should probably be mentioned in the docs of tj/serve.

**Comment by yuchi** [comment]
In fact I currently solved it by installing 1.x.

**Comment by leo** [comment]
According to the SemVer spec, we acted just right. Consider this change a complete rewrite of the package (which, in turn, is considered a major/breaking SemVer change).

Please use the old version of the package, if you'd like to take advantage of the functionalities that existed before the "rewrite".

:blush:

**Comment by derhuerst** [comment]
@yuchi Would you submit a PR at tj/serve to clarify in the docs that `server>=2` is in a different repo?

**Comment by yuchi** [comment]
@leo that's right. Obviously right. *But* a small note should do the job.

**Comment by yuchi** [comment]
@derhuerst I will.
