### ISSUE TITLE
TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by ilyaskarim** [zeit/serve#594]
Steps to reproduce:

1. Create a CRA app.
2. Build the app.
3. Install serve globally 
4. Serve by: `sudo serve --debug` npx version: 11.3.0

Error:

TypeError: Cannot read property 'code' of undefined
    at getMostRecent (/usr/lib/node_modules/serve/node_modules/update-check/index.js:125:11)

Also when to go running server:

This site can’t provide a secure connectionlocalhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by zacanger** [comment]
Looking at the code in update-check, that might've been a temporary error. It might be worth filing an issue over on [that repo](https://github.com/zeit/update-check/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) though. Also you shouldn't need to run `serve` with `sudo`, and try going to your localhost url without HTTPS.
