### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by modulexcite** [zeit/serve#60]
Thank you for yet another excellent project.
Is this supported on Windows? I'm trying to run this on Windows 7 64bit and the following error is returned by serve. Any help would be greatly appreciated.

**serve -h**
or 
**serve**

```
C:\Users\mattjs\AppData\Roaming\npm\node_modules\serve\dist\bin\serve:163
      const directoryPath = [...pathParts];
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by jamo** [comment]
which node version do you have? `node -v`

**Comment by calebboyd** [comment]
It looks like node v6 is the minimum supported. (based on the code and babel-configuration)

**Comment by derhuerst** [comment]
It would be good to add an `engines` field to `package.json`. NPM warns then afaik.

**Comment by modulexcite** [comment]
Sorry about that, I'm currently using node v4.4.7. I guess it's time to do an upgrade. Thank for your help.
