### ISSUE TITLE
Using --single with a specified directory

### ISSUE THREAD

**Issue by KnisterPeter** [zeit/serve#72]
Currently serve does not work with an cmdline option without parameter as the last but one argument and a directory as last argument.
The last but one argument (e.g. `--single`) then 'eats'  the last argument.

**Comment by KnisterPeter** [comment]
It does work with `--` given in the arguments list. But that is not intuitive.
For example `serve --single -- ./directory`

**Comment by leo** [comment]
@KnisterPeter `serve ./directory --single`
