### ISSUE TITLE
Allow omitting`.html` extension when serving `html` files

### ISSUE THREAD

**Issue by callumflack** [zeit/serve#79]
Ability to render 2nd level pages that aren't named `index.html`

See this test, built with [harpjs](https://github.com/sintaxi/harp): https://pw-kfgpxlxjho.now.sh

While `/work` renders, `work/oceanblue-living` does not.

Source view is enabled: https://pw-kfgpxlxjho.now.sh/_src

**Comment by leo** [comment]
Please place an `index.html` inside a sub directory named "oceanblue-living".
