### ISSUE TITLE
Default port 3000

### ISSUE THREAD

**Issue by bdadam** [zeit/serve#82]
I have been using the old `serve` library for quite a long time now. I was surprised that this package replaced the one from TJ.

There is one major difference which is quite disturbing for me. The old `serve` used to listen on port 3000 per default. Couldn't we somehow restore that behavior?

I know that this package copies a URL with the current port to the clipboard. But I liked that I can just stop the server, do something, restart it and the already open tab in the browser just works fine after reloading.

Any thoughts on this request?

**Comment by leo** [comment]
`serve -p 3000` 😊

**Comment by bdadam** [comment]
Thanks @leo, I know... this issue is about making `-p 3000` the default behavior and the current one would need opt-in.

**Comment by leo** [comment]
@bdadam You can configure your bash profile file to set the `PORT` env variable... :blush:

[More details](http://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables)

**Comment by bdadam** [comment]
Oh thanks, @leo. I didn't see that `PORT` is respected. That sounds good.

**Comment by squarewave24** [comment]
> `serve --port 3000` or `serve -p 3000` 😊

would have been great if this was included in their documentation 
https://github.com/zeit/serve-handler
