### ISSUE TITLE
Better info section

### ISSUE THREAD

**Issue by leo** [zeit/serve#85]
This needs to be better. Looks like it's designed for devs (shouldn't be the case)!

<img width="551" alt="screen shot 2017-01-23 at 17 56 08" src="https://cloud.githubusercontent.com/assets/6170607/22213652/4b9ce262-e195-11e6-8ebd-5b44ffdf41bc.png">

**Comment by albinekb** [comment]
What is your suggestion, how should it look? @leo 🤔

**Comment by derhuerst** [comment]
Is the port relevant? For all production-grade deployments, this will probably run behind a proxy like nginx which has different ports anyways. For all dev-deployments, people will know what ports are and how they work.

Regarding the hostname, I'd argue that it is irrelevant as well, since you only get this message if you've already found the server.

**Comment by leo** [comment]
We could improve security by hiding the version number, IP and port.

I honestly just want to mention that it's using serve. Or maybe even hide it completely?

**Comment by albinekb** [comment]
~improve~ obscure 😉  yes, but I think it's good advertising to have it there if nothing else

**Comment by leo** [comment]
> Running version 2.4.3 of serve

?

**Comment by derhuerst** [comment]
I think the node version is relevant enough and we don't want to support security by obscurity, so i prefer "[serve](#) x.x.x running on Node y.y.y".

**Comment by leo** [comment]
> node version is relevant enough

Relevant for what?

**Comment by derhuerst** [comment]
@leo

> Relevant for what? We're not running any custom code on there.

Just like the `serve` version, to see if both are up to date.

**Comment by leo** [comment]
> Serve 2.0.0 running on Node 7.0.0

Is perfect! Also "Serve" and "Node" should be linked.

**Comment by derhuerst** [comment]
And "serve" should be lower case, just like in the readme.

**Comment by leo** [comment]
@derhuerst Technically, yes. But it's the start of the sentence, so it looks pretty bad. In always capitalize in these cases... 🤔

**Comment by derhuerst** [comment]
@leo Interesting, I prefer the opposite. Feel like serve being a proprietary name itself is more important than it being at the beginning of the sentence. 😉

**Comment by timneutkens** [comment]
> Running serve 2.0.0 on Node 7.0.0
^ this might fix both your arguments 😜

**Comment by pablopunk** [comment]
I would just show

> Powered by Serve

IMO the user shouldn't care about the port (which is in the URL) or node version. Linking the name `Serve` to the github page should be enough if they are curious about it.

**Comment by derhuerst** [comment]
Another idea:

Showing nothing would bother less in 99% of the page views. For those who are interested, we can respond with a [`Server` header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.38) or `https://github.com/zeit/serve`.

**Comment by leo** [comment]
Yea let's hide this shit and hand the web a present! + Header ❤️
