### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by leo** [zeit/serve#86]
For loading `serve` inside an app

**Comment by timneutkens** [comment]
That would be really cool 👍

**Comment by dar5hak** [comment]
Hi everyone. I want to work on this.

Going through the code, I see that when using the CLI, we determine the args and the directory by [line 43](https://github.com/zeit/serve/blob/master/bin/serve.js#L43) in `bin/serve.js`.

A high-level solution, I think, would be to extract the rest of the file into a function that accepts `flags` and `directory` as arguments. We could then just export that function as the API.

What are your thoughts on this?

**Comment by leo** [comment]
@dar5hak Great idea! Maybe we can even keep the CLI like it is and just let the programmatic API run the CLI as a command using `child_process.spawn` or `child_process.exec` + setting the flags by setting `process.argv`. 🤔

**Comment by dar5hak** [comment]
@leo Oh yes! That would be simpler. I'll send a pull request tonight (UTC+0530).

Would you prefer an `index.js` at the project root, or inside `lib/`?

**Comment by leo** [comment]
@dar5hak A file named `api.js` inside `lib/`... 😊
