### ISSUE TITLE
Serve help doesn't work 

### ISSUE THREAD

**Issue by whitef0x0** [zeit/serve#94]
When I run `serve help`, it just tries to serve a `help` folder in my local directory.

Aka the output becomes `serving /Users/admin/Documents/vue-drag-and-drop/help on port 3000`

**Comment by timneutkens** [comment]
Good catch! Should be `serve --help`. Fixing now.

**Comment by leo** [comment]
^

**Comment by whitef0x0** [comment]
@timneutkens I'm running 3.2.2 on MacOS 10.11.6

**Comment by whitef0x0** [comment]
Nevermind. Fixed itself with an update.

**Comment by timneutkens** [comment]
😄
